CREATE TABLE [Demo].[Raw.OpenFlights.Plane]
(
	[Name] [nvarchar](128) NULL,
	[IATA Code] [nvarchar](128) NULL,
	[ICAO Code] [nvarchar](128) NULL
)

INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Aerospatiale/Alenia ATR 42-300', N'AT4', N'AT43')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Aerospatiale/Alenia ATR 42-500', N'AT5', N'AT45')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Aerospatiale/Alenia ATR 42-600', N'ATR', N'AT46')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Aerospatiale/Alenia ATR 72', N'AT7', N'AT72')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A300', N'AB3', N'A30B')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A300-600', N'ABY', N'A306')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A310', N'310', N'A310')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A318', N'318', N'A318')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A319', N'319', N'A319')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A320', N'320', N'A320')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A321', N'321', N'A321')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A330', N'330', N'\N')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A330-200', N'332', N'A332')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A330-300', N'333', N'A333')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A340', N'340', N'\N')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A340-200', N'342', N'A342')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A340-300', N'343', N'A343')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A340-500', N'345', N'A345')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A340-600', N'346', N'A346')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A350', N'350', N'\N')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A350-1000', N'351', N'A35K')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A350-900', N'359', N'A359')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A380', N'380', N'\N')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Airbus A380-800', N'388', N'A388')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Antonov An-148', N'A81', N'A148')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Antonov An-158', N'A58', N'A158')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Antonov AN-72', N'AN7', N'AN72')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Avro RJ100', N'AR1', N'RJ1H')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Avro RJ70', N'AR7', N'RJ70')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Avro RJ85', N'AR8', N'RJ85')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'BAe 146', N'146', N'\N')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'BAe 146-100', N'141', N'B461')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'BAe 146-200', N'142', N'B462')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'BAe 146-300', N'143', N'B463')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Beechcraft 1900', N'BEH', N'B190')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Beechcraft Baron', N'\N', N'BE58')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Bell 212', N'BH2', N'B212')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 707', N'703', N'B703')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 717', N'717', N'B712')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 720B', N'B72', N'B720')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 727', N'727', N'\N')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 727-100', N'721', N'B721')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 727-200', N'722', N'B722')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 737', N'737', N'\N')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 737 MAX 8', N'7M8', N'B38M')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 737-200', N'732', N'B732')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 737-300', N'733', N'B733')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 737-400', N'734', N'B734')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 737-500', N'735', N'B735')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 737-600', N'736', N'B736')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 737-700', N'73G', N'B737')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 737-800', N'738', N'B738')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 737-900', N'739', N'B739')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 747', N'747', N'\N')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 747-100', N'741', N'B741')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 747-200', N'742', N'B742')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 747-300', N'743', N'B743')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 747-400', N'744', N'B744')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 747-8', N'748', N'B748')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 747SP', N'74L', N'B74S')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 747SR', N'74R', N'B74R')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 757', N'757', N'\N')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 757-200', N'752', N'B752')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 757-300', N'753', N'B753')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 767', N'767', N'\N')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 767-200', N'762', N'B762')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 767-300', N'763', N'B763')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 767-400', N'764', N'B764')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 777', N'777', N'\N')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 777-200', N'772', N'B772')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 777-200LR', N'77L', N'B77L')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 777-300', N'773', N'B773')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 777-300ER', N'77W', N'B77W')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 787', N'787', N'\N')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 787-10', N'78J', N'B78X')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 787-8', N'788', N'B788')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Boeing 787-9', N'789', N'B789')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Bombardier CS100', N'CS1', N'BCS1')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Bombardier CS300', N'CS3', N'BCS3')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Bombardier Global Express', N'CCX', N'GLEX')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'British Aerospace ATP', N'ATP', N'ATP')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'British Aerospace Jetstream 31', N'J31', N'JS31')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'British Aerospace Jetstream 32', N'J32', N'JS32')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'British Aerospace Jetstream 41', N'J41', N'JS41')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Canadair CL-44', N'CL4', N'CL44')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Canadair Regional Jet 100', N'CR1', N'CRJ1')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Canadair Regional Jet 1000', N'CRK', N'CRJX')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Canadair Regional Jet 200', N'CR2', N'CRJ2')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Canadair Regional Jet 700', N'CR7', N'CRJ7')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Canadair Regional Jet 900', N'CR9', N'CRJ9')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Cessna 172', N'CN1', N'C172')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Cessna 182 Skylane', N'CN1', N'C182')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Cessna 208 Caravan', N'CN1', N'C208')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Cessna 210 Centurion', N'CN1', N'C210')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Cessna Citation CJ3', N'CNJ', N'C25B')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Cessna Citation CJ4', N'CNJ', N'C25C')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Cessna Citation Excel', N'CNJ', N'C56X')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Cessna Citation I', N'CNJ', N'C500')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Cessna Citation II', N'CNJ', N'C550')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Cessna Citation Mustang', N'CNJ', N'C510')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Cessna Citation Sovereign', N'CNJ', N'C680')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Cessna Citation X', N'CNJ', N'C750')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'COMAC C-919', N'\N', N'C919')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Concorde', N'SSC', N'CONC')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Dassault Falcon 2000', N'D20', N'F2TH')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Dassault Falcon 7X', N'DF7', N'FA7X')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'De Havilland Canada DHC-4 Caribou', N'DHC', N'DHC4')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'De Havilland Canada DHC-6 Twin Otter', N'DHT', N'DHC6')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'De Havilland Canada DHC-7 Dash 7', N'DH7', N'DHC7')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'De Havilland Canada DHC-8-300 Dash 8', N'DH3', N'DH8C')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'De Havilland Canada DHC-8-400 Dash 8Q', N'DH4', N'DH8D')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Douglas DC-10', N'D10', N'DC10')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Douglas DC-3', N'D3F', N'DC3')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Douglas DC-6', N'D6F', N'DC6')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Douglas DC-9-10', N'D91', N'DC91')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Douglas DC-9-30', N'D93', N'DC93')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Douglas DC-9-40', N'D94', N'DC94')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Douglas DC-9-50', N'D95', N'DC95')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Embraer 170', N'E70', N'E170')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Embraer 190', N'E90', N'E190')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Embraer 195', N'E95', N'E195')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Embraer EMB 110 Bandeirante', N'EMB', N'E110')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Embraer EMB 120 Brasilia', N'EM2', N'E120')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Embraer Legacy 600', N'ER3', N'E35L')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Embraer Phenom 100', N'EP1', N'E50P')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Embraer Phenom 300', N'EP3', N'E55P')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Embraer RJ135', N'ER3', N'E135')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Embraer RJ140', N'ERD', N'E135')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Embraer RJ145', N'ER4', N'E145')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Fairchild Dornier 328JET', N'FRJ', N'J328')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Fairchild Dornier Do.228', N'D28', N'D228')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Fairchild Dornier Do.328', N'D38', N'D328')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Fokker 100', N'100', N'F100')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Fokker 50', N'F50', N'F50')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Fokker 70', N'F70', N'F70')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Fokker F27 Friendship', N'F27', N'F27')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Gulfstream IV', N'GJ4', N'GLF4')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Gulfstream V', N'GJ5', N'GLF5')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Harbin Yunshuji Y12', N'YN2', N'Y12')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Hawker Siddeley HS 748', N'HS7', N'A748')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Ilyushin IL18', N'IL8', N'IL18')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Ilyushin IL62', N'IL6', N'IL62')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Ilyushin IL76', N'IL7', N'IL76')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Ilyushin IL86', N'ILW', N'IL86')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Ilyushin IL96', N'I93', N'IL96')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Learjet 35', N'LRJ', N'LJ35')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Learjet 60', N'LRJ', N'LJ60')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Lockheed L-188 Electra', N'LOE', N'L188')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'McDonnell Douglas MD-11', N'M11', N'MD11')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'McDonnell Douglas MD-81', N'M81', N'MD81')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'McDonnell Douglas MD-82', N'M82', N'MD82')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'McDonnell Douglas MD-83', N'M83', N'MD83')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'McDonnell Douglas MD-87', N'M87', N'MD87')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'McDonnell Douglas MD-88', N'M88', N'MD88')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'McDonnell Douglas MD-90', N'M90', N'MD90')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'NAMC YS-11', N'YS1', N'YS11')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Partenavia P.68', N'PN6', N'P68')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Pilatus Britten-Norman BN-2A Mk III Trislander', N'BNT', N'TRIS')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Pilatus Britten-Norman BN-2A/B Islander', N'BNI', N'BN2P')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Pilatus PC-12', N'PL2', N'PC12')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Pilatus PC-6 Turbo Porter', N'PL6', N'PC6T')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Piper PA-31 Navajo', N'PA2', N'PA31')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Saab 2000', N'S20', N'SB20')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Saab SF340A/B', N'SF3', N'SF34')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Shorts SD.360', N'SH6', N'SH36')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Sikorsky S-61', N'S61', N'S61')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Sikorsky S-76', N'S76', N'S76')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Sukhoi Superjet 100-95', N'SU9', N'SU95')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Tupolev Tu-134', N'TU3', N'T134')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Tupolev Tu-144', N'\N', N'T144')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Tupolev Tu-154', N'TU5', N'T154')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Tupolev Tu-204', N'T20', N'T204')
INSERT [Demo].[Raw.OpenFlights.Plane] ([Name], [IATA Code], [ICAO Code]) VALUES (N'Yakovlev Yak-40', N'YK4', N'YK40')
