// Do not modify this file. It's generated by Framework.Cli.

namespace DatabaseBuiltIn.dbo
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Database.dbo;

    public static class FrameworkConfigGridBuiltInTableApplicationCli
    {
        public static List<FrameworkConfigGridBuiltIn> RowList
        {
            get
            {
                var result = new List<FrameworkConfigGridBuiltIn>();
                result.Add(new FrameworkConfigGridBuiltIn() { Id = 3, IdName = "Demo.Language; ", TableId = 14, TableIdName = "Demo.Language", TableNameCSharp = "Demo.Language", ConfigName = null, RowCountMax = null, IsAllowInsert = null, IsExist = true });
                result.Add(new FrameworkConfigGridBuiltIn() { Id = 4, IdName = "Demo.Navigation; ", TableId = 29, TableIdName = "Demo.Navigation", TableNameCSharp = "Demo.Navigation", ConfigName = null, RowCountMax = 20, IsAllowInsert = null, IsExist = true });
                result.Add(new FrameworkConfigGridBuiltIn() { Id = 5, IdName = "Demo.RawOpenFlightsAirport; ", TableId = 34, TableIdName = "Demo.RawOpenFlightsAirport", TableNameCSharp = "Demo.RawOpenFlightsAirport", ConfigName = null, RowCountMax = null, IsAllowInsert = null, IsExist = true });
                result.Add(new FrameworkConfigGridBuiltIn() { Id = 6, IdName = "Demo.RawWikipediaAircraft; ", TableId = 36, TableIdName = "Demo.RawWikipediaAircraft", TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, RowCountMax = 5, IsAllowInsert = null, IsExist = true });
                result.Add(new FrameworkConfigGridBuiltIn() { Id = 7, IdName = "Demo.RawWikipediaAircraft; G", TableId = 36, TableIdName = "Demo.RawWikipediaAircraft", TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", RowCountMax = 5, IsAllowInsert = null, IsExist = true });
                result.Add(new FrameworkConfigGridBuiltIn() { Id = 8, IdName = "Demo.RoadmapDisplay; ", TableId = 42, TableIdName = "Demo.RoadmapDisplay", TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, RowCountMax = 20, IsAllowInsert = null, IsExist = true });
                return result;
            }
        }
    }

    public static class FrameworkConfigFieldBuiltInTableApplicationCli
    {
        public static List<FrameworkConfigFieldBuiltIn> RowList
        {
            get
            {
                var result = new List<FrameworkConfigFieldBuiltIn>();
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 19, ConfigGridId = 4, ConfigGridIdName = "Demo.Navigation; ", FieldId = 179, FieldIdName = "Demo.Navigation; Id", InstanceName = null, TableNameCSharp = "Demo.Navigation", ConfigName = null, FieldNameCSharp = "Id", Text = null, Description = null, IsVisible = true, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 20, ConfigGridId = 4, ConfigGridIdName = "Demo.Navigation; ", FieldId = 183, FieldIdName = "Demo.Navigation; PageName", InstanceName = null, TableNameCSharp = "Demo.Navigation", ConfigName = null, FieldNameCSharp = "PageName", Text = "PAGE", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 21, ConfigGridId = 4, ConfigGridIdName = "Demo.Navigation; ", FieldId = 180, FieldIdName = "Demo.Navigation; ParentId", InstanceName = null, TableNameCSharp = "Demo.Navigation", ConfigName = null, FieldNameCSharp = "ParentId", Text = null, Description = null, IsVisible = true, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 22, ConfigGridId = 5, ConfigGridIdName = "Demo.RawOpenFlightsAirport; ", FieldId = 208, FieldIdName = "Demo.RawOpenFlightsAirport; AirportID", InstanceName = null, TableNameCSharp = "Demo.RawOpenFlightsAirport", ConfigName = null, FieldNameCSharp = "AirportID", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 23, ConfigGridId = 5, ConfigGridIdName = "Demo.RawOpenFlightsAirport; ", FieldId = 210, FieldIdName = "Demo.RawOpenFlightsAirport; City", InstanceName = null, TableNameCSharp = "Demo.RawOpenFlightsAirport", ConfigName = null, FieldNameCSharp = "City", Text = "My City", Description = "This is the city of the airport", IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 24, ConfigGridId = 6, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 226, FieldIdName = "Demo.RawWikipediaAircraft; IataCode", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "IataCode", Text = "IATA Code", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 25, ConfigGridId = 7, ConfigGridIdName = "Demo.RawWikipediaAircraft; G", FieldId = 226, FieldIdName = "Demo.RawWikipediaAircraft; IataCode", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", FieldNameCSharp = "IataCode", Text = "IATA Code", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 26, ConfigGridId = 7, ConfigGridIdName = "Demo.RawWikipediaAircraft; G", FieldId = 225, FieldIdName = "Demo.RawWikipediaAircraft; IcaoCode", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", FieldNameCSharp = "IcaoCode", Text = "ICAO Code", Description = null, IsVisible = null, IsReadOnly = true, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 27, ConfigGridId = 6, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 225, FieldIdName = "Demo.RawWikipediaAircraft; IcaoCode", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "IcaoCode", Text = "ICAO Code", Description = null, IsVisible = null, IsReadOnly = true, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 28, ConfigGridId = 6, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 227, FieldIdName = "Demo.RawWikipediaAircraft; Model", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "Model", Text = "Image", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 29, ConfigGridId = 7, ConfigGridIdName = "Demo.RawWikipediaAircraft; G", FieldId = 227, FieldIdName = "Demo.RawWikipediaAircraft; Model", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", FieldNameCSharp = "Model", Text = "Image", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 30, ConfigGridId = 7, ConfigGridIdName = "Demo.RawWikipediaAircraft; G", FieldId = 230, FieldIdName = "Demo.RawWikipediaAircraft; ModelImageUrl", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", FieldNameCSharp = "ModelImageUrl", Text = "Image Link", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 31, ConfigGridId = 6, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 230, FieldIdName = "Demo.RawWikipediaAircraft; ModelImageUrl", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "ModelImageUrl", Text = "Image Link", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 32, ConfigGridId = 6, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 229, FieldIdName = "Demo.RawWikipediaAircraft; ModelTitle", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "ModelTitle", Text = "Title", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 33, ConfigGridId = 7, ConfigGridIdName = "Demo.RawWikipediaAircraft; G", FieldId = 229, FieldIdName = "Demo.RawWikipediaAircraft; ModelTitle", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", FieldNameCSharp = "ModelTitle", Text = "Title", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 34, ConfigGridId = 7, ConfigGridIdName = "Demo.RawWikipediaAircraft; G", FieldId = 228, FieldIdName = "Demo.RawWikipediaAircraft; ModelUrl", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", FieldNameCSharp = "ModelUrl", Text = "Url", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 35, ConfigGridId = 6, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 228, FieldIdName = "Demo.RawWikipediaAircraft; ModelUrl", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "ModelUrl", Text = "Url", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 36, ConfigGridId = 8, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 292, FieldIdName = "Demo.RoadmapDisplay; LoginUserText", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "LoginUserText", Text = "User", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 37, ConfigGridId = 8, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 281, FieldIdName = "Demo.RoadmapDisplay; Name", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "Name", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 38, ConfigGridId = 8, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 285, FieldIdName = "Demo.RoadmapDisplay; RoadmapCategoryIdName", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapCategoryIdName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 39, ConfigGridId = 8, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 284, FieldIdName = "Demo.RoadmapDisplay; RoadmapCategoryText", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapCategoryText", Text = "Category", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 40, ConfigGridId = 8, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 287, FieldIdName = "Demo.RoadmapDisplay; RoadmapModuleText", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapModuleText", Text = "Module", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 41, ConfigGridId = 8, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 290, FieldIdName = "Demo.RoadmapDisplay; RoadmapPriorityIdName", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapPriorityIdName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 42, ConfigGridId = 8, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 289, FieldIdName = "Demo.RoadmapDisplay; RoadmapPriorityText", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapPriorityText", Text = "Priority", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 43, ConfigGridId = 8, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 296, FieldIdName = "Demo.RoadmapDisplay; RoadmapStateIdName", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapStateIdName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Sort = null, IsExist = true });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 44, ConfigGridId = 8, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 295, FieldIdName = "Demo.RoadmapDisplay; RoadmapStateText", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapStateText", Text = "State", Description = null, IsVisible = null, IsReadOnly = null, Sort = null, IsExist = true });
                return result;
            }
        }
    }
}

namespace DatabaseBuiltIn.Demo
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Database.Demo;

    public static class NavigationBuiltInTableApplicationCli
    {
        public static List<NavigationBuiltIn> RowList
        {
            get
            {
                var result = new List<NavigationBuiltIn>();
                result.Add(new NavigationBuiltIn() { Id = 1, IdName = "About", ParentId = null, ParentIdName = null, Name = "About", TextHtml = "<i class=\"fas fa-bullhorn\"></i> About", PageName = "About", Sort = 9.6 });
                result.Add(new NavigationBuiltIn() { Id = 5, IdName = "Airplane", ParentId = 2, ParentIdName = "Home", Name = "Airplane", TextHtml = "<i class=\"fas fa-plane\"></i> Airplane", PageName = "Home", Sort = 0.2 });
                result.Add(new NavigationBuiltIn() { Id = 6, IdName = "Airport", ParentId = 2, ParentIdName = "Home", Name = "Airport", TextHtml = "<i class=\"fas fa-plane-departure\"></i> Airport", PageName = "Airport", Sort = 0.1 });
                result.Add(new NavigationBuiltIn() { Id = 2, IdName = "Home", ParentId = null, ParentIdName = null, Name = "Home", TextHtml = "<i class=\"fas fa-home\"></i> Home", PageName = null, Sort = 1 });
                result.Add(new NavigationBuiltIn() { Id = 7, IdName = "LoginProfile", ParentId = 3, ParentIdName = "LoginUser", Name = "LoginProfile", TextHtml = "<i class=\"far fa-id-card\"></i> Profile", PageName = null, Sort = 2 });
                result.Add(new NavigationBuiltIn() { Id = 8, IdName = "LoginRoleManagement", ParentId = 3, ParentIdName = "LoginUser", Name = "LoginRoleManagement", TextHtml = "<i class=\'fas fa-hat-cowboy\'></i> Role Management", PageName = "LoginRole", Sort = 2.5 });
                result.Add(new NavigationBuiltIn() { Id = 9, IdName = "LoginSignIn", ParentId = 3, ParentIdName = "LoginUser", Name = "LoginSignIn", TextHtml = "<i class=\"fas fa-sign-in-alt\"></i> Sign In", PageName = null, Sort = 1 });
                result.Add(new NavigationBuiltIn() { Id = 10, IdName = "LoginSignOut", ParentId = 3, ParentIdName = "LoginUser", Name = "LoginSignOut", TextHtml = "<i class=\"fas fa-sign-out-alt\"></i> Sign Out", PageName = null, Sort = 3 });
                result.Add(new NavigationBuiltIn() { Id = 3, IdName = "LoginUser", ParentId = null, ParentIdName = null, Name = "LoginUser", TextHtml = "<i class=\"fas fa-user\"></i> User", PageName = null, Sort = 10 });
                result.Add(new NavigationBuiltIn() { Id = 11, IdName = "LoginUserManagement", ParentId = 3, ParentIdName = "LoginUser", Name = "LoginUserManagement", TextHtml = "<i class=\"fas fa-user\"></i> User Management", PageName = "LoginUser", Sort = 2.4 });
                result.Add(new NavigationBuiltIn() { Id = 4, IdName = "Roadmap", ParentId = null, ParentIdName = null, Name = "Roadmap", TextHtml = "<i class=\"fas fa-road\"></i> Roadmap", PageName = "Roadmap", Sort = 9 });
                return result;
            }
        }
    }

    public static class LoginPermissionBuiltInTableApplicationCli
    {
        public static List<LoginPermissionBuiltIn> RowList
        {
            get
            {
                var result = new List<LoginPermissionBuiltIn>();
                result.Add(new LoginPermissionBuiltIn() { Id = 4, IdName = "AirportPage Show", Name = "AirportPage Show", Description = "Allows user to see airport page.", IsBuiltIn = false, IsExist = true });
                result.Add(new LoginPermissionBuiltIn() { Id = 5, IdName = "Calendar Modify", Name = "Calendar Modify", Description = "Allows user to modify the calendar.", IsBuiltIn = false, IsExist = true });
                result.Add(new LoginPermissionBuiltIn() { Id = 6, IdName = "Language Modify", Name = "Language Modify", Description = "Allows user to add new languages.", IsBuiltIn = false, IsExist = true });
                result.Add(new LoginPermissionBuiltIn() { Id = 7, IdName = "Roadmap Modify", Name = "Roadmap Modify", Description = "Allows user to modify the development roadmap.", IsBuiltIn = false, IsExist = true });
                return result;
            }
        }
    }

    public static class LoginRoleBuiltInTableApplicationCli
    {
        public static List<LoginRoleBuiltIn> RowList
        {
            get
            {
                var result = new List<LoginRoleBuiltIn>();
                result.Add(new LoginRoleBuiltIn() { Id = 1, IdName = "Administrator", Name = "Administrator", Description = "Administrator role" });
                result.Add(new LoginRoleBuiltIn() { Id = 2, IdName = "BackOffice", Name = "BackOffice", Description = "Power user" });
                result.Add(new LoginRoleBuiltIn() { Id = 3, IdName = "Developer", Name = "Developer", Description = "Developer role" });
                result.Add(new LoginRoleBuiltIn() { Id = 4, IdName = "Guest", Name = "Guest", Description = "Guest user (not logged in)" });
                return result;
            }
        }
    }

    public static class LoginRolePermissionBuiltInTableApplicationCli
    {
        public static List<LoginRolePermissionBuiltIn> RowList
        {
            get
            {
                var result = new List<LoginRolePermissionBuiltIn>();
                result.Add(new LoginRolePermissionBuiltIn() { Id = 1, RoleId = 1, RoleIdName = "Administrator", PermissionId = 1, PermissionIdName = "Administrator", IsActive = true });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 2, RoleId = 1, RoleIdName = "Administrator", PermissionId = 4, PermissionIdName = "AirportPage Show", IsActive = true });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 3, RoleId = 1, RoleIdName = "Administrator", PermissionId = 5, PermissionIdName = "Calendar Modify", IsActive = true });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 4, RoleId = 1, RoleIdName = "Administrator", PermissionId = 6, PermissionIdName = "Language Modify", IsActive = true });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 5, RoleId = 1, RoleIdName = "Administrator", PermissionId = 7, PermissionIdName = "Roadmap Modify", IsActive = true });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 6, RoleId = 2, RoleIdName = "BackOffice", PermissionId = 5, PermissionIdName = "Calendar Modify", IsActive = true });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 7, RoleId = 2, RoleIdName = "BackOffice", PermissionId = 7, PermissionIdName = "Roadmap Modify", IsActive = true });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 8, RoleId = 3, RoleIdName = "Developer", PermissionId = 1, PermissionIdName = "Administrator", IsActive = true });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 9, RoleId = 3, RoleIdName = "Developer", PermissionId = 2, PermissionIdName = "Developer", IsActive = true });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 10, RoleId = 3, RoleIdName = "Developer", PermissionId = 3, PermissionIdName = "Guest", IsActive = true });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 11, RoleId = 4, RoleIdName = "Guest", PermissionId = 4, PermissionIdName = "AirportPage Show", IsActive = true });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 12, RoleId = 4, RoleIdName = "Guest", PermissionId = 5, PermissionIdName = "Calendar Modify", IsActive = false });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 13, RoleId = 4, RoleIdName = "Guest", PermissionId = 3, PermissionIdName = "Guest", IsActive = true });
                result.Add(new LoginRolePermissionBuiltIn() { Id = 14, RoleId = 4, RoleIdName = "Guest", PermissionId = 7, PermissionIdName = "Roadmap Modify", IsActive = false });
                return result;
            }
        }
    }

    public static class LoginUserBuiltInTableApplicationCli
    {
        public static List<LoginUserBuiltIn> RowList
        {
            get
            {
                var result = new List<LoginUserBuiltIn>();
                result.Add(new LoginUserBuiltIn() { Id = 1, IdName = "Administrator", Name = "Administrator", Password = null, IsBuiltIn = true, IsExist = true });
                result.Add(new LoginUserBuiltIn() { Id = 2, IdName = "Developer", Name = "Developer", Password = "dev55", IsBuiltIn = true, IsExist = true });
                result.Add(new LoginUserBuiltIn() { Id = 3, IdName = "Guest", Name = "Guest", Password = "Guest33", IsBuiltIn = true, IsExist = true });
                result.Add(new LoginUserBuiltIn() { Id = 4, IdName = "John", Name = "John", Password = "J33", IsBuiltIn = false, IsExist = true });
                result.Add(new LoginUserBuiltIn() { Id = 5, IdName = "Marc", Name = "Marc", Password = "DAdkm", IsBuiltIn = false, IsExist = true });
                return result;
            }
        }
    }

    public static class LoginUserRoleBuiltInTableApplicationCli
    {
        public static List<LoginUserRoleBuiltIn> RowList
        {
            get
            {
                var result = new List<LoginUserRoleBuiltIn>();
                result.Add(new LoginUserRoleBuiltIn() { Id = 1, UserId = 1, UserIdName = "Administrator", RoleId = 1, RoleIdName = "Administrator", IsActive = true });
                result.Add(new LoginUserRoleBuiltIn() { Id = 2, UserId = 1, UserIdName = "Administrator", RoleId = 2, RoleIdName = "BackOffice", IsActive = true });
                result.Add(new LoginUserRoleBuiltIn() { Id = 3, UserId = 1, UserIdName = "Administrator", RoleId = 4, RoleIdName = "Guest", IsActive = true });
                result.Add(new LoginUserRoleBuiltIn() { Id = 4, UserId = 2, UserIdName = "Developer", RoleId = 3, RoleIdName = "Developer", IsActive = true });
                result.Add(new LoginUserRoleBuiltIn() { Id = 5, UserId = 3, UserIdName = "Guest", RoleId = 1, RoleIdName = "Administrator", IsActive = false });
                result.Add(new LoginUserRoleBuiltIn() { Id = 6, UserId = 3, UserIdName = "Guest", RoleId = 2, RoleIdName = "BackOffice", IsActive = false });
                result.Add(new LoginUserRoleBuiltIn() { Id = 7, UserId = 3, UserIdName = "Guest", RoleId = 4, RoleIdName = "Guest", IsActive = true });
                result.Add(new LoginUserRoleBuiltIn() { Id = 8, UserId = 4, UserIdName = "John", RoleId = 2, RoleIdName = "BackOffice", IsActive = true });
                result.Add(new LoginUserRoleBuiltIn() { Id = 9, UserId = 4, UserIdName = "John", RoleId = 4, RoleIdName = "Guest", IsActive = null });
                result.Add(new LoginUserRoleBuiltIn() { Id = 10, UserId = 5, UserIdName = "Marc", RoleId = 4, RoleIdName = "Guest", IsActive = true });
                return result;
            }
        }
    }

    public static class RoadmapModuleBuiltInTableApplicationCli
    {
        public static List<RoadmapModuleBuiltIn> RowList
        {
            get
            {
                var result = new List<RoadmapModuleBuiltIn>();
                result.Add(new RoadmapModuleBuiltIn() { Id = 1, IdName = "Application", Name = "Application", Text = "Application", Description = null, IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapModuleBuiltIn() { Id = 2, IdName = "ApplicationCms", Name = "ApplicationCms", Text = "Application / Cms", Description = null, IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapModuleBuiltIn() { Id = 3, IdName = "ApplicationLogin", Name = "ApplicationLogin", Text = "Application / Login", Description = null, IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapModuleBuiltIn() { Id = 4, IdName = "ApplicationRoadmap", Name = "ApplicationRoadmap", Text = "Application / Roadmap", Description = null, IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapModuleBuiltIn() { Id = 5, IdName = "Framework", Name = "Framework", Text = "Framework", Description = null, IsBuiltIn = true, IsExist = true });
                return result;
            }
        }
    }

    public static class RoadmapBuiltInTableApplicationCli
    {
        public static List<RoadmapBuiltIn> RowList
        {
            get
            {
                var result = new List<RoadmapBuiltIn>();
                result.Add(new RoadmapBuiltIn() { Id = 1, Name = Guid.Parse("27e60a75-cfa5-420b-b316-093b1feef57f"), Description = "Lookup data grid annotation", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 1, RoadmapCategoryIdName = "Analyze", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 3, RoadmapPriorityIdName = "Low", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 2, Name = Guid.Parse("16e14652-e075-4759-938c-0e9ebe736928"), Description = "Show alert loading during server side render", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 1, RoadmapCategoryIdName = "Analyze", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 3, RoadmapPriorityIdName = "Low", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 3, Name = Guid.Parse("f628779a-2871-42f4-b0da-11ee9f25b826"), Description = "DateTime filter on data grid not working", Date = DateTime.Parse("2020-03-03 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 2, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 1, RoadmapPriorityIdName = "Critical", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 2, RoadmapStateIdName = "In Progress", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 4, Name = Guid.Parse("607f4e9d-f178-4922-bc4f-1d12ed9e26f2"), Description = "Roadmap date column", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 4, RoadmapModuleIdName = "ApplicationRoadmap", RoadmapPriorityId = 2, RoadmapPriorityIdName = "High", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 1, RoadmapStateIdName = "Done", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 5, Name = Guid.Parse("d7e1f5cd-648b-4c18-8fe9-2b95bd474ae9"), Description = "Excel import", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 3, RoadmapPriorityIdName = "Low", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 6, Name = Guid.Parse("860bb46c-385c-45d2-8a6f-52774dac5414"), Description = "Detect browser css grid support on startup", Date = DateTime.Parse("2020-02-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 3, RoadmapPriorityIdName = "Low", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 7, Name = Guid.Parse("60d25167-d113-42a5-89f9-62d83850a032"), Description = "Update Angular 9", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 3, RoadmapPriorityIdName = "Low", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 8, Name = Guid.Parse("c6e421fa-8f78-424d-9e0f-64da942e740f"), Description = "Method Data.Update(); if two users modified same record.", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 2, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 3, RoadmapPriorityIdName = "Low", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 9, Name = Guid.Parse("f562829c-d023-4ba7-99fc-65361c887c65"), Description = "Roadmap done annotation with check", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 4, RoadmapModuleIdName = "ApplicationRoadmap", RoadmapPriorityId = 2, RoadmapPriorityIdName = "High", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 1, RoadmapStateIdName = "Done", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 10, Name = Guid.Parse("1412dfe5-6d8e-42c9-8576-72d5e18618f2"), Description = "Calendar with holidays", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 1, RoadmapModuleIdName = "Application", RoadmapPriorityId = 3, RoadmapPriorityIdName = "Low", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 11, Name = Guid.Parse("18f7de7a-c22d-40f6-989e-79604b0bced6"), Description = "Cli command generate for Date", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 2, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 1, RoadmapPriorityIdName = "Critical", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 1, RoadmapStateIdName = "Done", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 12, Name = Guid.Parse("b9af7ea7-51b1-4613-b9d8-7c28b8fe617a"), Description = "Data grid with tab scroll to next column", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 3, RoadmapPriorityIdName = "Low", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 13, Name = Guid.Parse("0acc2649-e499-4c3d-a329-7e6282747973"), Description = "Cell multiline", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 3, RoadmapPriorityIdName = "Low", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 14, Name = Guid.Parse("9e392c19-56c4-4008-8481-8426765068d9"), Description = "Update annotation for whole data row after user text modify", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 2, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 2, RoadmapPriorityIdName = "High", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 15, Name = Guid.Parse("0680161a-d0df-4b3a-9ad0-8c402ea97945"), Description = "Roadmap add number", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 4, RoadmapModuleIdName = "ApplicationRoadmap", RoadmapPriorityId = 4, RoadmapPriorityIdName = "Medium", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 16, Name = Guid.Parse("2b51d3f1-078d-4f37-aad4-9e9b7c4fa08b"), Description = "User sign up (register)", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 3, RoadmapModuleIdName = "ApplicationLogin", RoadmapPriorityId = 4, RoadmapPriorityIdName = "Medium", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 17, Name = Guid.Parse("ba7a91fe-8a09-45ab-a3f5-a4f94bceb86d"), Description = "Roadmap priority color annotation", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 4, RoadmapModuleIdName = "ApplicationRoadmap", RoadmapPriorityId = 2, RoadmapPriorityIdName = "High", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 1, RoadmapStateIdName = "Done", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 18, Name = Guid.Parse("0b61b5bd-0405-4512-af42-b7d5a5eb104a"), Description = "Setting class", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 3, RoadmapPriorityIdName = "Low", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 19, Name = Guid.Parse("23514dee-f766-42a3-8cf6-c5b828fb09fe"), Description = "User profile", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 3, RoadmapModuleIdName = "ApplicationLogin", RoadmapPriorityId = 4, RoadmapPriorityIdName = "Medium", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 20, Name = Guid.Parse("35e50249-67ae-49bb-91b3-c77ff53909ce"), Description = "Roadmap annotation for Framework (Chip) and Application (Tablet)", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 4, RoadmapModuleIdName = "ApplicationRoadmap", RoadmapPriorityId = 2, RoadmapPriorityIdName = "High", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 21, Name = Guid.Parse("4ef7e1d7-eeb3-4cf0-bbb5-cd52428c9caa"), Description = "Lookup do not select first row", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 2, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 2, RoadmapPriorityIdName = "High", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 4, RoadmapStateIdName = "Open", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 22, Name = Guid.Parse("cd93b089-87d0-4ec0-9ce1-d17d431b335e"), Description = "Html Snippet", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 1, RoadmapCategoryIdName = "Analyze", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 3, RoadmapPriorityIdName = "Low", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 23, Name = Guid.Parse("79585835-ac66-43dc-a04d-df4b955d98e6"), Description = "Google code prettify", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 2, RoadmapModuleIdName = "ApplicationCms", RoadmapPriorityId = 3, RoadmapPriorityIdName = "Low", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 24, Name = Guid.Parse("f45a2a50-3933-452c-9195-dfb21d5b02bc"), Description = "AppDoc CMS", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 4, RoadmapPriorityIdName = "Medium", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 25, Name = Guid.Parse("b8db4e1a-97c8-4044-b514-e15576bf46d4"), Description = "Lookup window on same data row (for example roadmap)", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 2, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 1, RoadmapPriorityIdName = "Critical", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                result.Add(new RoadmapBuiltIn() { Id = 26, Name = Guid.Parse("da61059f-e91b-4379-bb13-f69731a2ea4c"), Description = "Upload image (Framework image database table)", Date = DateTime.Parse("2020-03-02 00:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 3, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 5, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 2, RoadmapPriorityIdName = "High", LoginUserId = 2, LoginUserIdName = "Developer", RoadmapStateId = 3, RoadmapStateIdName = "New", IsBuiltIn = true, IsExist = true });
                return result;
            }
        }
    }
}
