// Do not modify this file. It's generated by Framework.Cli generate command.

namespace DatabaseIntegrate.dbo
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Database.dbo;

    /// <summary>
    /// Integrate Sql=[dbo].[FrameworkConfigGridIntegrate]; Assembly=Cli;
    /// </summary>
    public static class FrameworkConfigGridIntegrateAppCli
    {
        public static List<FrameworkConfigGridIntegrate> RowList
        {
            get
            {
                var result = new List<FrameworkConfigGridIntegrate>
                {
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "Demo.CmsComponentDisplay; ", TableId = 0, TableIdName = "Demo.CmsComponentDisplay", TableNameCSharp = "Demo.CmsComponentDisplay", ConfigName = null, RowCountMax = null, WidthMax = null, IsAllowInsert = null, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "Demo.CmsFile; ", TableId = 0, TableIdName = "Demo.CmsFile", TableNameCSharp = "Demo.CmsFile", ConfigName = null, RowCountMax = null, WidthMax = null, IsAllowInsert = null, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "Demo.Language; ", TableId = 0, TableIdName = "Demo.Language", TableNameCSharp = "Demo.Language", ConfigName = null, RowCountMax = null, WidthMax = null, IsAllowInsert = null, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "Demo.Navigation; ", TableId = 0, TableIdName = "Demo.Navigation", TableNameCSharp = "Demo.Navigation", ConfigName = null, RowCountMax = 20, WidthMax = null, IsAllowInsert = null, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "Demo.RawOpenFlightsAirport; ", TableId = 0, TableIdName = "Demo.RawOpenFlightsAirport", TableNameCSharp = "Demo.RawOpenFlightsAirport", ConfigName = null, RowCountMax = null, WidthMax = null, IsAllowInsert = null, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "Demo.RawWikipediaAircraft; ", TableId = 0, TableIdName = "Demo.RawWikipediaAircraft", TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, RowCountMax = 5, WidthMax = null, IsAllowInsert = null, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "Demo.RawWikipediaAircraft; G", TableId = 0, TableIdName = "Demo.RawWikipediaAircraft", TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", RowCountMax = 5, WidthMax = null, IsAllowInsert = null, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "Demo.RoadmapDisplay; ", TableId = 0, TableIdName = "Demo.RoadmapDisplay", TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, RowCountMax = 20, WidthMax = null, IsAllowInsert = null, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "Demo.ShopProductPhoto; ", TableId = 0, TableIdName = "Demo.ShopProductPhoto", TableNameCSharp = "Demo.ShopProductPhoto", ConfigName = null, RowCountMax = null, WidthMax = null, IsAllowInsert = null, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                    new FrameworkConfigGridIntegrate { Id = 0, IdName = "Demo.StorageFile; ", TableId = 0, TableIdName = "Demo.StorageFile", TableNameCSharp = "Demo.StorageFile", ConfigName = null, RowCountMax = null, WidthMax = null, IsAllowInsert = null, IsShowHeader = null, IsShowPagination = null, IsDelete = false },
                };
                return result;
            }
        }
    }

    /// <summary>
    /// Integrate Sql=[dbo].[FrameworkConfigFieldIntegrate]; Assembly=Cli;
    /// </summary>
    public static class FrameworkConfigFieldIntegrateAppCli
    {
        public static List<FrameworkConfigFieldIntegrate> RowList
        {
            get
            {
                var result = new List<FrameworkConfigFieldIntegrate>
                {
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.CmsComponentDisplay; ", FieldId = 0, FieldIdName = "Demo.CmsComponentDisplay; Id", InstanceName = null, TableNameCSharp = "Demo.CmsComponentDisplay", ConfigName = null, FieldNameCSharp = "Id", Text = null, Description = null, IsVisible = true, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.CmsComponentDisplay; ", FieldId = 0, FieldIdName = "Demo.CmsComponentDisplay; ParentId", InstanceName = null, TableNameCSharp = "Demo.CmsComponentDisplay", ConfigName = null, FieldNameCSharp = "ParentId", Text = null, Description = null, IsVisible = true, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.CmsFile; ", FieldId = 0, FieldIdName = "Demo.CmsFile; Data", InstanceName = null, TableNameCSharp = "Demo.CmsFile", ConfigName = null, FieldNameCSharp = "Data", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.Navigation; ", FieldId = 0, FieldIdName = "Demo.Navigation; Id", InstanceName = null, TableNameCSharp = "Demo.Navigation", ConfigName = null, FieldNameCSharp = "Id", Text = null, Description = null, IsVisible = true, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.Navigation; ", FieldId = 0, FieldIdName = "Demo.Navigation; PageName", InstanceName = null, TableNameCSharp = "Demo.Navigation", ConfigName = null, FieldNameCSharp = "PageName", Text = "PAGE", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.Navigation; ", FieldId = 0, FieldIdName = "Demo.Navigation; ParentId", InstanceName = null, TableNameCSharp = "Demo.Navigation", ConfigName = null, FieldNameCSharp = "ParentId", Text = null, Description = null, IsVisible = true, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawOpenFlightsAirport; ", FieldId = 0, FieldIdName = "Demo.RawOpenFlightsAirport; AirportID", InstanceName = null, TableNameCSharp = "Demo.RawOpenFlightsAirport", ConfigName = null, FieldNameCSharp = "AirportID", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawOpenFlightsAirport; ", FieldId = 0, FieldIdName = "Demo.RawOpenFlightsAirport; City", InstanceName = null, TableNameCSharp = "Demo.RawOpenFlightsAirport", ConfigName = null, FieldNameCSharp = "City", Text = "My City", Description = "This is the city of the airport", IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 0, FieldIdName = "Demo.RawWikipediaAircraft; IataCode", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "IataCode", Text = "IATA Code", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawWikipediaAircraft; G", FieldId = 0, FieldIdName = "Demo.RawWikipediaAircraft; IataCode", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", FieldNameCSharp = "IataCode", Text = "IATA Code", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawWikipediaAircraft; G", FieldId = 0, FieldIdName = "Demo.RawWikipediaAircraft; IcaoCode", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", FieldNameCSharp = "IcaoCode", Text = "ICAO Code", Description = null, IsVisible = null, IsReadOnly = true, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 0, FieldIdName = "Demo.RawWikipediaAircraft; IcaoCode", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "IcaoCode", Text = "ICAO Code", Description = null, IsVisible = null, IsReadOnly = true, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 0, FieldIdName = "Demo.RawWikipediaAircraft; Model", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "Model", Text = "Image", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawWikipediaAircraft; G", FieldId = 0, FieldIdName = "Demo.RawWikipediaAircraft; Model", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", FieldNameCSharp = "Model", Text = "Image", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawWikipediaAircraft; G", FieldId = 0, FieldIdName = "Demo.RawWikipediaAircraft; ModelImageUrl", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", FieldNameCSharp = "ModelImageUrl", Text = "Image Link", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 0, FieldIdName = "Demo.RawWikipediaAircraft; ModelImageUrl", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "ModelImageUrl", Text = "Image Link", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 0, FieldIdName = "Demo.RawWikipediaAircraft; ModelTitle", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "ModelTitle", Text = "Title", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawWikipediaAircraft; G", FieldId = 0, FieldIdName = "Demo.RawWikipediaAircraft; ModelTitle", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", FieldNameCSharp = "ModelTitle", Text = "Title", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawWikipediaAircraft; G", FieldId = 0, FieldIdName = "Demo.RawWikipediaAircraft; ModelUrl", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = "G", FieldNameCSharp = "ModelUrl", Text = "Url", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 0, FieldIdName = "Demo.RawWikipediaAircraft; ModelUrl", InstanceName = null, TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "ModelUrl", Text = "Url", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 0, FieldIdName = "Demo.RoadmapDisplay; LoginUserText", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "LoginUserText", Text = "User", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 0, FieldIdName = "Demo.RoadmapDisplay; Name", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "Name", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 0, FieldIdName = "Demo.RoadmapDisplay; RoadmapCategoryIdName", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapCategoryIdName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 0, FieldIdName = "Demo.RoadmapDisplay; RoadmapCategoryText", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapCategoryText", Text = "Category", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 0, FieldIdName = "Demo.RoadmapDisplay; RoadmapModuleIdName", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapModuleIdName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 0, FieldIdName = "Demo.RoadmapDisplay; RoadmapModuleText", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapModuleText", Text = "Module", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 0, FieldIdName = "Demo.RoadmapDisplay; RoadmapPriorityIdName", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapPriorityIdName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 0, FieldIdName = "Demo.RoadmapDisplay; RoadmapPriorityText", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapPriorityText", Text = "Priority", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 0, FieldIdName = "Demo.RoadmapDisplay; RoadmapStateIdName", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapStateIdName", Text = null, Description = null, IsVisible = false, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.RoadmapDisplay; ", FieldId = 0, FieldIdName = "Demo.RoadmapDisplay; RoadmapStateText", InstanceName = null, TableNameCSharp = "Demo.RoadmapDisplay", ConfigName = null, FieldNameCSharp = "RoadmapStateText", Text = "State", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = null, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.ShopProductPhoto; ", FieldId = 0, FieldIdName = "Demo.ShopProductPhoto; Data", InstanceName = null, TableNameCSharp = "Demo.ShopProductPhoto", ConfigName = null, FieldNameCSharp = "Data", Text = "Image", Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = 2, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.ShopProductPhoto; ", FieldId = 0, FieldIdName = "Demo.ShopProductPhoto; FileName", InstanceName = null, TableNameCSharp = "Demo.ShopProductPhoto", ConfigName = null, FieldNameCSharp = "FileName", Text = null, Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = 1, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.StorageFile; ", FieldId = 0, FieldIdName = "Demo.StorageFile; FileName", InstanceName = "Link", TableNameCSharp = "Demo.StorageFile", ConfigName = null, FieldNameCSharp = "FileName", Text = "Link", Description = "Link to file", IsVisible = false, IsReadOnly = true, Width = null, IsMultiline = null, Sort = 1, IsDelete = false },
                    new FrameworkConfigFieldIntegrate { Id = 0, ConfigGridId = 0, ConfigGridIdName = "Demo.StorageFile; ", FieldId = 0, FieldIdName = "Demo.StorageFile; FileName", InstanceName = null, TableNameCSharp = "Demo.StorageFile", ConfigName = null, FieldNameCSharp = "FileName", Text = null, Description = null, IsVisible = null, IsReadOnly = null, Width = null, IsMultiline = null, Sort = 0, IsDelete = false },
                };
                return result;
            }
        }
    }
}

namespace DatabaseIntegrate.Demo
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using Database.Demo;

    /// <summary>
    /// Integrate Sql=[Demo].[NavigationIntegrate]; Assembly=Cli;
    /// </summary>
    public static class NavigationIntegrateAppCli
    {
        public static List<NavigationIntegrate> RowList
        {
            get
            {
                var result = new List<NavigationIntegrate>
                {
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "About", TextHtml = "<i class=\"fas fa-bullhorn\"></i> About", PageName = "About", Sort = 9.6, IdName = "About", ParentIdName = null },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "Airplane", TextHtml = "<i class=\"fas fa-plane\"></i> Airplane", PageName = "Home", Sort = 0.2, IdName = "Airplane", ParentIdName = "Home" },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "Airport", TextHtml = "<i class=\"fas fa-plane-departure\"></i> Airport", PageName = "Airport", Sort = 0.1, IdName = "Airport", ParentIdName = "Home" },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "Cms", TextHtml = "<i class=\'fas fa-pencil-alt\'></i> Cms", PageName = null, Sort = 9.55, IdName = "Cms", ParentIdName = null },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "CmsDoc", TextHtml = "<i class=\'fas fa-book\'></i> Doc", PageName = null, Sort = 1, IdName = "CmsDoc", ParentIdName = "Cms" },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "CmsFile", TextHtml = "<i class=\'far fa-file\'></i> Cms File", PageName = null, Sort = 1, IdName = "CmsFile", ParentIdName = "Cms" },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "FileManager", TextHtml = "<i class=\'far fa-file\'></i> File Manager", PageName = null, Sort = 9.5, IdName = "FileManager", ParentIdName = null },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "Home", TextHtml = "<i class=\"fas fa-home\"></i> Home", PageName = null, Sort = 1, IdName = "Home", ParentIdName = null },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "LoginProfile", TextHtml = "<i class=\"far fa-id-card\"></i> Profile", PageName = null, Sort = 2, IdName = "LoginProfile", ParentIdName = "LoginUser" },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "LoginRoleManagement", TextHtml = "<i class=\'fas fa-hat-cowboy\'></i> Role Management", PageName = "LoginRole", Sort = 2.5, IdName = "LoginRoleManagement", ParentIdName = "LoginUser" },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "LoginSignIn", TextHtml = "<i class=\"fas fa-sign-in-alt\"></i> Sign In", PageName = null, Sort = 1, IdName = "LoginSignIn", ParentIdName = "LoginUser" },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "LoginSignOut", TextHtml = "<i class=\"fas fa-sign-out-alt\"></i> Sign Out", PageName = null, Sort = 3, IdName = "LoginSignOut", ParentIdName = "LoginUser" },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "LoginUser", TextHtml = "<i class=\"fas fa-user\"></i> User", PageName = null, Sort = 10, IdName = "LoginUser", ParentIdName = null },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "LoginUserManagement", TextHtml = "<i class=\"fas fa-user\"></i> User Management", PageName = "LoginUser", Sort = 2.4, IdName = "LoginUserManagement", ParentIdName = "LoginUser" },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "Roadmap", TextHtml = "<i class=\"fas fa-road\"></i> Roadmap", PageName = "Roadmap", Sort = 9.55, IdName = "Roadmap", ParentIdName = null },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "Shop", TextHtml = "<i class=\'fas fa-store\'></i> Shop", PageName = null, Sort = 8.9, IdName = "Shop", ParentIdName = null },
                    new NavigationIntegrate { Id = 0, ParentId = 0, Name = "ShopCart", TextHtml = "<i class=\'fas fa-shopping-cart\'></i> Cart", PageName = null, Sort = 1, IdName = "ShopCart", ParentIdName = "Shop" },
                };
                return result;
            }
        }
    }

    /// <summary>
    /// Integrate Sql=[Demo].[LoginPermissionIntegrate]; Assembly=Cli;
    /// </summary>
    public static class LoginPermissionIntegrateAppCli
    {
        public static List<LoginPermissionIntegrate> RowList
        {
            get
            {
                var result = new List<LoginPermissionIntegrate>
                {
                    new LoginPermissionIntegrate { Id = 0, IdName = "AirportPage Show", Name = "AirportPage Show", Description = "Allows user to see airport page.", IsIntegrate = false, IsDelete = false },
                    new LoginPermissionIntegrate { Id = 0, IdName = "Calendar Modify", Name = "Calendar Modify", Description = "Allows user to modify the calendar.", IsIntegrate = false, IsDelete = false },
                    new LoginPermissionIntegrate { Id = 0, IdName = "Language Modify", Name = "Language Modify", Description = "Allows user to add new languages.", IsIntegrate = false, IsDelete = false },
                    new LoginPermissionIntegrate { Id = 0, IdName = "Roadmap Modify", Name = "Roadmap Modify", Description = "Allows user to modify the development roadmap.", IsIntegrate = false, IsDelete = false },
                };
                return result;
            }
        }
    }

    /// <summary>
    /// Integrate Sql=[Demo].[LoginRoleIntegrate]; Assembly=Cli;
    /// </summary>
    public static class LoginRoleIntegrateAppCli
    {
        public static List<LoginRoleIntegrate> RowList
        {
            get
            {
                var result = new List<LoginRoleIntegrate>
                {
                    new LoginRoleIntegrate { Id = 0, IdName = "Administrator", Name = "Administrator", Description = "Administrator role" },
                    new LoginRoleIntegrate { Id = 0, IdName = "BackOffice", Name = "BackOffice", Description = "Power user" },
                    new LoginRoleIntegrate { Id = 0, IdName = "Developer", Name = "Developer", Description = "Developer role" },
                    new LoginRoleIntegrate { Id = 0, IdName = "Guest", Name = "Guest", Description = "Guest user (not logged in)" },
                };
                return result;
            }
        }
    }

    /// <summary>
    /// Integrate Sql=[Demo].[LoginRolePermissionIntegrate]; Assembly=Cli;
    /// </summary>
    public static class LoginRolePermissionIntegrateAppCli
    {
        public static List<LoginRolePermissionIntegrate> RowList
        {
            get
            {
                var result = new List<LoginRolePermissionIntegrate>
                {
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "Administrator", PermissionId = 0, PermissionIdName = "Administrator", IsActive = true },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "Administrator", PermissionId = 0, PermissionIdName = "AirportPage Show", IsActive = true },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "Administrator", PermissionId = 0, PermissionIdName = "Calendar Modify", IsActive = true },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "Administrator", PermissionId = 0, PermissionIdName = "Language Modify", IsActive = true },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "Administrator", PermissionId = 0, PermissionIdName = "Roadmap Modify", IsActive = true },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "BackOffice", PermissionId = 0, PermissionIdName = "Calendar Modify", IsActive = true },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "BackOffice", PermissionId = 0, PermissionIdName = "Roadmap Modify", IsActive = true },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "Developer", PermissionId = 0, PermissionIdName = "Administrator", IsActive = true },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "Developer", PermissionId = 0, PermissionIdName = "Developer", IsActive = true },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "Developer", PermissionId = 0, PermissionIdName = "Guest", IsActive = true },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "Guest", PermissionId = 0, PermissionIdName = "AirportPage Show", IsActive = true },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "Guest", PermissionId = 0, PermissionIdName = "Calendar Modify", IsActive = false },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "Guest", PermissionId = 0, PermissionIdName = "Guest", IsActive = true },
                    new LoginRolePermissionIntegrate { Id = 0, RoleId = 0, RoleIdName = "Guest", PermissionId = 0, PermissionIdName = "Roadmap Modify", IsActive = false },
                };
                return result;
            }
        }
    }

    /// <summary>
    /// Integrate Sql=[Demo].[LoginUserIntegrate]; Assembly=Cli;
    /// </summary>
    public static class LoginUserIntegrateAppCli
    {
        public static List<LoginUserIntegrate> RowList
        {
            get
            {
                var result = new List<LoginUserIntegrate>
                {
                    new LoginUserIntegrate { Id = 0, IdName = "Administrator", Name = "Administrator", Password = null, IsIntegrate = true, IsDelete = false },
                    new LoginUserIntegrate { Id = 0, IdName = "Developer", Name = "Developer", Password = "dev55", IsIntegrate = true, IsDelete = false },
                    new LoginUserIntegrate { Id = 0, IdName = "Guest", Name = "Guest", Password = "Guest33", IsIntegrate = true, IsDelete = false },
                    new LoginUserIntegrate { Id = 0, IdName = "John", Name = "John", Password = "J33", IsIntegrate = false, IsDelete = false },
                    new LoginUserIntegrate { Id = 0, IdName = "Marc", Name = "Marc", Password = "DAdkm", IsIntegrate = false, IsDelete = false },
                };
                return result;
            }
        }
    }

    /// <summary>
    /// Integrate Sql=[Demo].[LoginUserRoleIntegrate]; Assembly=Cli;
    /// </summary>
    public static class LoginUserRoleIntegrateAppCli
    {
        public static List<LoginUserRoleIntegrate> RowList
        {
            get
            {
                var result = new List<LoginUserRoleIntegrate>
                {
                    new LoginUserRoleIntegrate { Id = 0, UserId = 0, UserIdName = "Administrator", RoleId = 0, RoleIdName = "Administrator", IsActive = true },
                    new LoginUserRoleIntegrate { Id = 0, UserId = 0, UserIdName = "Administrator", RoleId = 0, RoleIdName = "BackOffice", IsActive = true },
                    new LoginUserRoleIntegrate { Id = 0, UserId = 0, UserIdName = "Administrator", RoleId = 0, RoleIdName = "Guest", IsActive = true },
                    new LoginUserRoleIntegrate { Id = 0, UserId = 0, UserIdName = "Developer", RoleId = 0, RoleIdName = "Developer", IsActive = true },
                    new LoginUserRoleIntegrate { Id = 0, UserId = 0, UserIdName = "Guest", RoleId = 0, RoleIdName = "Administrator", IsActive = false },
                    new LoginUserRoleIntegrate { Id = 0, UserId = 0, UserIdName = "Guest", RoleId = 0, RoleIdName = "BackOffice", IsActive = false },
                    new LoginUserRoleIntegrate { Id = 0, UserId = 0, UserIdName = "Guest", RoleId = 0, RoleIdName = "Guest", IsActive = true },
                    new LoginUserRoleIntegrate { Id = 0, UserId = 0, UserIdName = "John", RoleId = 0, RoleIdName = "BackOffice", IsActive = true },
                    new LoginUserRoleIntegrate { Id = 0, UserId = 0, UserIdName = "John", RoleId = 0, RoleIdName = "Guest", IsActive = null },
                    new LoginUserRoleIntegrate { Id = 0, UserId = 0, UserIdName = "Marc", RoleId = 0, RoleIdName = "Guest", IsActive = true },
                };
                return result;
            }
        }
    }

    /// <summary>
    /// Integrate Sql=[Demo].[RoadmapIntegrate]; Assembly=Cli;
    /// </summary>
    public static class RoadmapIntegrateAppCli
    {
        public static List<RoadmapIntegrate> RowList
        {
            get
            {
                var result = new List<RoadmapIntegrate>
                {
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("30c70c9e-d8dd-4eeb-8c5e-0130ecc89566"), Number = 1, Description = "CMS Glossary", Date = DateTime.Parse("2020-03-06 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "ApplicationCms", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("d16e4409-df8a-4f52-9f3e-073a8b4a4646"), Number = 2, Description = "Method AppJson.FileDownloadSecure(); deserialize session --> FileDownloadSessionAsync", Date = DateTime.Parse("2020-03-06 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("27e60a75-cfa5-420b-b316-093b1feef57f"), Number = 3, Description = "Lookup data grid annotation", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Analyze", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("74bf2fbc-897e-40c8-8a3c-0d816f143712"), Number = 4, Description = "File Manager open file and navigate back. Wrong data in grid. Only in Chrome. Not in Edge. --> Set input autocomplete off.", Date = DateTime.Parse("2020-03-06 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Critical", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("16e14652-e075-4759-938c-0e9ebe736928"), Number = 5, Description = "Show alert message loading during server side render", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Analyze", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("f628779a-2871-42f4-b0da-11ee9f25b826"), Number = 6, Description = "DateTime filter on data grid not working", Date = DateTime.Parse("2020-03-03 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Critical", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("607f4e9d-f178-4922-bc4f-1d12ed9e26f2"), Number = 7, Description = "Roadmap date column", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "ApplicationRoadmap", RoadmapPriorityId = 0, RoadmapPriorityIdName = "High", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("c6927785-5a37-4e4b-b141-25f423f6b9e8"), Number = 8, Description = "Cli command open. For example sql script folder, website folder, angular folder", Date = DateTime.Parse("2020-04-17 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("2a471c0d-42d6-48ce-a3aa-28b0f3333e01"), Number = 9, Description = "Cli generate for column varbinary(MAX) with byte[] and byte[]? (Allow nulls)", Date = DateTime.Parse("2020-03-06 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Analyze", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("d7e1f5cd-648b-4c18-8fe9-2b95bd474ae9"), Number = 10, Description = "Excel import", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("26f7e199-de97-41f7-81a0-2d4a2797f4bd"), Number = 11, Description = "Validate ConfigCli.json FolderName and ConnectionString", Date = DateTime.Parse("2020-04-17 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("860bb46c-385c-45d2-8a6f-52774dac5414"), Number = 12, Description = "Detect browser css grid support on startup --> Changed back to html table", Date = DateTime.Parse("2020-02-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("fab64f74-2325-43e8-aefd-555d671fb68d"), Number = 13, Description = "Analyze RoadmapIntegrateTableApplicationCli text wrap in generated source code. Done and implemented.", Date = DateTime.Parse("2020-03-05 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Analyze", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Medium", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("518d3501-e6d9-4df4-8f23-562779f4106f"), Number = 14, Description = "Cli command deployDb reseed option for Integrate (DBCC checkident (\'Demo.CmsComponent\', reseed, 1000)", Date = DateTime.Parse("2020-04-16 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("e2283d41-9fdf-4003-8e17-59c468a2490e"), Number = 15, Description = "Data grid scroll up down with mouse wheel", Date = DateTime.Parse("2020-03-06 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "High", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("f57beadb-a507-4334-a7c9-5b5715324545"), Number = 16, Description = "Update grid filter on cell leave (TextLeave). For example enter date into grid filter and tab out.", Date = DateTime.Parse("2020-03-05 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Medium", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("59d8dc96-b882-458a-bd9e-5e09afb8ece8"), Number = 17, Description = "Diff match patch for response. (https://github.com/google/diff-match-patch) - (https://neil.fraser.name/software/diff_match_patch/demos/patch.html) ", Date = DateTime.Parse("2020-04-15 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("59f092a7-8489-4b88-a185-5fa709e79e44"), Number = 18, Description = "Cli command config test ConnectionString", Date = DateTime.Parse("2020-04-16 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("60d25167-d113-42a5-89f9-62d83850a032"), Number = 19, Description = "Update Angular 9", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("c6e421fa-8f78-424d-9e0f-64da942e740f"), Number = 20, Description = "Method Data.Update(); if two users modified same record.", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("f562829c-d023-4ba7-99fc-65361c887c65"), Number = 21, Description = "Roadmap done annotation with check", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "ApplicationRoadmap", RoadmapPriorityId = 0, RoadmapPriorityIdName = "High", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("b275f250-74e2-4c10-9735-6997c03a90e8"), Number = 22, Description = "Show json session size for all active sessions in a datagrid", Date = DateTime.Parse("2020-04-17 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("1412dfe5-6d8e-42c9-8576-72d5e18618f2"), Number = 23, Description = "Calendar with holidays", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Application", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("18f7de7a-c22d-40f6-989e-79604b0bced6"), Number = 24, Description = "Cli command generate for Date", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Critical", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("b9af7ea7-51b1-4613-b9d8-7c28b8fe617a"), Number = 25, Description = "Data grid with tab scroll to next column", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("0acc2649-e499-4c3d-a329-7e6282747973"), Number = 26, Description = "Cell multiline", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("9e392c19-56c4-4008-8481-8426765068d9"), Number = 27, Description = "Update annotation for whole data row after user text modify", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "High", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("0680161a-d0df-4b3a-9ad0-8c402ea97945"), Number = 28, Description = "Roadmap add number for example (#23) for every item.", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "ApplicationRoadmap", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Medium", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("d74ab84c-d0b0-4568-9762-9233c9979974"), Number = 29, Description = "Display row summary at bottom of data grid. Useful when scrolling horizontally", Date = DateTime.Parse("2020-03-06 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("2b51d3f1-078d-4f37-aad4-9e9b7c4fa08b"), Number = 30, Description = "User sign up (register)", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "ApplicationLogin", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Medium", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("ba7a91fe-8a09-45ab-a3f5-a4f94bceb86d"), Number = 31, Description = "Roadmap priority color annotation", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "ApplicationRoadmap", RoadmapPriorityId = 0, RoadmapPriorityIdName = "High", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("0b61b5bd-0405-4512-af42-b7d5a5eb104a"), Number = 32, Description = "Setting class. Can be set on ConfigCli.json for example IsBootstrap --> CssFrameworkEnum", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("a28fdc6e-6b0a-4796-aab6-c42a6ff0feb8"), Number = 33, Description = "Uom in filter index and new. Delete text for example (2kg)", Date = DateTime.Parse("2020-03-06 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Analyze", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("23514dee-f766-42a3-8cf6-c5b828fb09fe"), Number = 34, Description = "User profile", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "ApplicationLogin", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Medium", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("35e50249-67ae-49bb-91b3-c77ff53909ce"), Number = 35, Description = "Roadmap annotation for Framework (Chip) and Application (Tablet)", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "ApplicationRoadmap", RoadmapPriorityId = 0, RoadmapPriorityIdName = "High", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("ce1ecc6e-0e6c-4bb8-9f22-cb122220e539"), Number = 36, Description = "Method AppJson.Navigate(); to directly navigate to a page", Date = DateTime.Parse("2020-03-06 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("4ef7e1d7-eeb3-4cf0-bbb5-cd52428c9caa"), Number = 37, Description = "Lookup do not select first row", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Critical", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("cd93b089-87d0-4ec0-9ce1-d17d431b335e"), Number = 38, Description = "Html Snippet. Done and implemented with CustomComponent", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Analyze", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("850b76a9-0fa6-424f-a01a-da607c3f6a5e"), Number = 39, Description = "Json serialize byte[] and byte[]? and UnitTest", Date = DateTime.Parse("2020-03-06 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Analyze", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("79585835-ac66-43dc-a04d-df4b955d98e6"), Number = 40, Description = "Google code prettify, Prismjs", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "ApplicationCms", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("f45a2a50-3933-452c-9195-dfb21d5b02bc"), Number = 41, Description = "AppDoc CMS", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "ApplicationCms", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Medium", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "In Progress", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("b8db4e1a-97c8-4044-b514-e15576bf46d4"), Number = 42, Description = "Lookup window on same data row (for example roadmap)", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Bug", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Critical", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("dc12020d-9b4d-4c6b-8a26-e985ee8ed574"), Number = 43, Description = "In roadmap show SELECT @@SERVERNAME. Done with new ConfigCli.json structure for environment. localhost and DEV ConnectionString are linked.", Date = DateTime.Parse("2020-03-06 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "ApplicationRoadmap", RoadmapPriorityId = 0, RoadmapPriorityIdName = "High", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("5dcbe94d-263e-4b8e-a112-e9bb5424039c"), Number = 44, Description = "Use Fontawesome (*.scss) and link it in MasterDefault. npm install --save @fortawesome/fontawesome-free; $fa-font-path: \"../node_modules/@fortawesome/fontawesome-free/webfonts/\"; @import \"../node_modules/@fortawesome/fontawesome-free/scss/fontawesome.scss\"; @import \"../node_modules/@fortawesome/fontawesome-free/scss/solid.scss\"; .frameworkUp { @extend .fas, .fa-caret-up; }", Date = DateTime.Parse("2020-04-15 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Analyze", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("da61059f-e91b-4379-bb13-f69731a2ea4c"), Number = 45, Description = "Upload image (Framework image database table)", Date = DateTime.Parse("2020-03-02 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "High", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "Done", IsIntegrate = true, IsDelete = false },
                    new RoadmapIntegrate { Id = 0, Name = Guid.Parse("8a87041b-764a-417d-af84-960d0e4a7d08"), Number = 46, Description = "Redirect http to https contact to contact/", Date = DateTime.Parse("2020-09-03 12:00", CultureInfo.InvariantCulture), RoadmapCategoryId = 0, RoadmapCategoryIdName = "Feature", RoadmapModuleId = 0, RoadmapModuleIdName = "Framework", RoadmapPriorityId = 0, RoadmapPriorityIdName = "Low", LoginUserId = 0, LoginUserIdName = "Developer", RoadmapStateId = 0, RoadmapStateIdName = "New", IsIntegrate = true, IsDelete = false },
                };
                return result;
            }
        }
    }

    /// <summary>
    /// Integrate Sql=[Demo].[StorageFile]; Assembly=Cli;
    /// </summary>
    public static class StorageFileAppCli
    {
        public static List<StorageFile> RowList
        {
            get
            {
                var result = new List<StorageFile>
                {
                    new StorageFile { Id = 0, FileName = "Game.png", Data = Framework.Cli.UtilCli.BlobReadData("Demo.StorageFile.Game.png"), Description = "Board image", IsIntegrate = true, IsDelete = false },
                    new StorageFile { Id = 0, FileName = "Hello World.pdf", Data = Framework.Cli.UtilCli.BlobReadData("Demo.StorageFile.Hello World.pdf"), Description = null, IsIntegrate = true, IsDelete = false },
                    new StorageFile { Id = 0, FileName = "Hello.txt", Data = Framework.Cli.UtilCli.BlobReadData("Demo.StorageFile.Hello.txt"), Description = "Some text", IsIntegrate = true, IsDelete = false },
                    new StorageFile { Id = 0, FileName = "House.png", Data = Framework.Cli.UtilCli.BlobReadData("Demo.StorageFile.House.png"), Description = "Wood house", IsIntegrate = true, IsDelete = false },
                };
                return result;
            }
        }
    }

    /// <summary>
    /// Integrate Sql=[Demo].[CmsCodeBlockTypeIntegrate]; Assembly=Cli;
    /// </summary>
    public static class CmsCodeBlockTypeIntegrateAppCli
    {
        public static List<CmsCodeBlockTypeIntegrate> RowList
        {
            get
            {
                var result = new List<CmsCodeBlockTypeIntegrate>
                {
                    new CmsCodeBlockTypeIntegrate { Id = 0, Name = "CSharp", FileExtension = "cs", Sort = 1, IdName = "CSharp" },
                    new CmsCodeBlockTypeIntegrate { Id = 0, Name = "Html", FileExtension = "html", Sort = 2, IdName = "Html" },
                    new CmsCodeBlockTypeIntegrate { Id = 0, Name = "JavaScript", FileExtension = "js", Sort = 3, IdName = "JavaScript" },
                    new CmsCodeBlockTypeIntegrate { Id = 0, Name = "Shell", FileExtension = "sh", Sort = 4, IdName = "Shell" },
                    new CmsCodeBlockTypeIntegrate { Id = 0, Name = "Sql", FileExtension = "sql", Sort = 5, IdName = "Sql" },
                };
                return result;
            }
        }
    }

    /// <summary>
    /// Integrate Sql=[Demo].[CmsFile]; Assembly=Cli;
    /// </summary>
    public static class CmsFileAppCli
    {
        public static List<CmsFile> RowList
        {
            get
            {
                var result = new List<CmsFile>
                {
                    new CmsFile { Id = 0, FileName = "Donky.png", Data = Framework.Cli.UtilCli.BlobReadData("Demo.CmsFile.Donky.png"), Text = "Two donkeys", SourceText = "Photo self", SourceLink = null, IsIntegrate = true, IsDelete = false },
                    new CmsFile { Id = 0, FileName = "Forrest.png", Data = Framework.Cli.UtilCli.BlobReadData("Demo.CmsFile.Forrest.png"), Text = "Forrest with lake", SourceText = "Photo self", SourceLink = null, IsIntegrate = true, IsDelete = false },
                    new CmsFile { Id = 0, FileName = "Install.gif", Data = Framework.Cli.UtilCli.BlobReadData("Demo.CmsFile.Install.gif"), Text = "Page Install", SourceText = null, SourceLink = "https://pixabay.com/vectors/box-carton-3d-software-package-149482/", IsIntegrate = true, IsDelete = false },
                    new CmsFile { Id = 0, FileName = "VisualStudioPrerequisite.png", Data = Framework.Cli.UtilCli.BlobReadData("Demo.CmsFile.VisualStudioPrerequisite.png"), Text = "Page Install - Prerequisite", SourceText = null, SourceLink = null, IsIntegrate = true, IsDelete = false },
                };
                return result;
            }
        }
    }

    /// <summary>
    /// Integrate Sql=[Demo].[CmsComponentIntegrate]; Assembly=Cli;
    /// </summary>
    public static class CmsComponentIntegrateAppCli
    {
        public static List<CmsComponentIntegrate> RowList
        {
            get
            {
                var result = new List<CmsComponentIntegrate>
                {
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("caca7d48-0cc5-45c2-9c6d-b552f3218253"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = "Getting Started", ParagraphText = "Web “Demo Application” is a comprehensive example to get started with. The following two components need to be installed on the machine as prerequisite:", ParagraphIsNote = null, BulletText = null, ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 1, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("caca7d48-0cc5-45c2-9c6d-b552f3218253"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Paragraph", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("7a5cf05e-cf7f-417e-8a77-e6b3c64c7690"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = null, ParagraphText = null, ParagraphIsNote = null, BulletText = "[Node.js](https://nodejs.org/en/) (LTS Version)", ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 2, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("7a5cf05e-cf7f-417e-8a77-e6b3c64c7690"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Bullet", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("0687af27-90d0-4bb5-a6a4-16858d2b7cb9"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = null, ParagraphText = null, ParagraphIsNote = null, BulletText = "[.NET Core](https://dotnet.microsoft.com/download) (Version 3.1)", ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 3, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("0687af27-90d0-4bb5-a6a4-16858d2b7cb9"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Bullet", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("5d151ce3-85e5-4263-a2df-444a4b37826e"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = "Tools", ParagraphText = "The web “Demo Application” can be started from command prompt without Visual Studio or other tools being installed. It needs only access to an MS-SQL Server. For code development the following tools are recommended:", ParagraphIsNote = null, BulletText = null, ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 4, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("5d151ce3-85e5-4263-a2df-444a4b37826e"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Paragraph", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("32c59732-b305-4cb2-8f80-34611d2746aa"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = null, ParagraphText = null, ParagraphIsNote = null, BulletText = "[MS-SQL Server](https://www.microsoft.com/en-us/sql-server/sql-server-downloads) (Works with developer edition). Install before VS See also: [stackexchange](https://dba.stackexchange.com/questions/190090/help-installing-sql-server-2017-vs-shell-installation-has-failed-with-exit-cod)", ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 5, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("32c59732-b305-4cb2-8f80-34611d2746aa"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Bullet", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("f5f1dd68-a613-478e-84c4-20adf9774c89"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = null, ParagraphText = null, ParagraphIsNote = null, BulletText = "[SQL Server Management Studio](https://docs.microsoft.com/sql/ssms/download-sql-server-management-studio-ssms) (SSMS)", ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 6, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("f5f1dd68-a613-478e-84c4-20adf9774c89"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Bullet", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("1a2447d6-479e-4606-ad4d-b99220daa0c0"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = null, ParagraphText = null, ParagraphIsNote = null, BulletText = "[Git](https://git-scm.com/downloads)", ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 7, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("1a2447d6-479e-4606-ad4d-b99220daa0c0"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Bullet", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("3cd11df6-72c6-4a20-aa14-28ff38ac3306"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = null, ParagraphText = null, ParagraphIsNote = null, BulletText = "[PoshGit](https://github.com/WorkplaceX/Research/tree/master/PoshGit) Git state visualization", ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 8, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("3cd11df6-72c6-4a20-aa14-28ff38ac3306"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Bullet", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("9367c885-35a3-47b7-b198-181c8b41aa05"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = null, ParagraphText = null, ParagraphIsNote = null, BulletText = "[Visual Studio](https://visualstudio.microsoft.com/vs/) (Works with community edition). Install the following component:", ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 9, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("9367c885-35a3-47b7-b198-181c8b41aa05"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Bullet", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("a0995865-56b7-4c3e-9f4a-cbf26db19ed7"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = null, ParagraphText = null, ParagraphIsNote = null, BulletText = null, ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 10, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("a0995865-56b7-4c3e-9f4a-cbf26db19ed7"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Image", PageImageFileIdName = null, ImageFileIdName = "VisualStudioPrerequisite.png", CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("344fdf88-650c-425a-943b-95442f264e9c"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = "Video Tutorial", ParagraphText = "Following short 2:30 minutes video shows step by step installation process of git clone, build, deploy and starting the web application.", ParagraphIsNote = null, BulletText = null, ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 11, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("344fdf88-650c-425a-943b-95442f264e9c"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Paragraph", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("f8e096b8-377c-422b-841c-f1d43524bde4"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = null, ParagraphText = null, ParagraphIsNote = null, BulletText = null, ImageFileId = 0, ImageText = null, YoutubeLink = "https://www.youtube.com/embed/bYJTl5axgUY", CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 12, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("f8e096b8-377c-422b-841c-f1d43524bde4"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Youtube", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("3326dd46-ce2d-409f-b4d1-1d75d7a3fec7"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = "Git Clone", ParagraphText = null, ParagraphIsNote = null, BulletText = null, ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 13, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("3326dd46-ce2d-409f-b4d1-1d75d7a3fec7"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "Paragraph", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("99683a4c-c16b-49bb-97fa-79478750bdbd"), ComponentTypeId = 0, PagePath = null, PageTitle = null, PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = null, ParagraphText = null, ParagraphIsNote = null, BulletText = null, ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = "git clone https://github.com/WorkplaceX/ApplicationDemo.git --recursive", CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = 14, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("99683a4c-c16b-49bb-97fa-79478750bdbd"), ParentIdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeIdName = "CodeBlock", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = "Shell" },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("ff06741f-0e2b-4237-98fd-73b2195735ba"), ComponentTypeId = 0, PagePath = "/", PageTitle = "Home", PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = null, ParagraphText = null, ParagraphIsNote = null, BulletText = null, ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = null, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("ff06741f-0e2b-4237-98fd-73b2195735ba"), ParentIdName = null, ComponentTypeIdName = "Page", PageImageFileIdName = null, ImageFileIdName = null, CodeBlockTypeIdName = null },
                    new CmsComponentIntegrate { Id = 0, ParentId = 0, Name = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ComponentTypeId = 0, PagePath = "/install/", PageTitle = "Install", PageImageFileId = 0, PageDate = null, PageTextMd = null, ParagraphTitle = null, ParagraphText = null, ParagraphIsNote = null, BulletText = null, ImageFileId = 0, ImageText = null, YoutubeLink = null, CodeBlockText = null, CodeBlockTypeId = 0, GlossaryTerm = null, GlossaryText = null, Sort = null, IsIntegrate = false, IsDelete = false, IdName = Guid.Parse("2cfe2bd4-34eb-48d7-ab7b-de145a8256a2"), ParentIdName = Guid.Parse("ff06741f-0e2b-4237-98fd-73b2195735ba"), ComponentTypeIdName = "Page", PageImageFileIdName = "Install.gif", ImageFileIdName = null, CodeBlockTypeIdName = null },
                };
                return result;
            }
        }
    }
}
