// Do not modify this file. It's generated by Framework.Cli.

namespace DatabaseBuiltIn.dbo
{
    using System.Collections.Generic;
    using Database.dbo;

    public static class FrameworkConfigGridBuiltInCli
    {
        public static List<FrameworkConfigGridBuiltIn> List
        {
            get
            {
                var result = new List<FrameworkConfigGridBuiltIn>();
                result.Add(new FrameworkConfigGridBuiltIn() { Id = 3, IdName = "Demo.RawWikipediaAircraft; ", TableId = 18, TableIdName = "Demo.RawWikipediaAircraft", TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, RowCountMax = 5, IsAllowInsert = null, IsExist = true });
                return result;
            }
        }
    }

    public static class FrameworkConfigFieldBuiltInCli
    {
        public static List<FrameworkConfigFieldBuiltIn> List
        {
            get
            {
                var result = new List<FrameworkConfigFieldBuiltIn>();
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 18, ConfigGridId = 3, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 130, FieldIdName = "Demo.RawWikipediaAircraft; IataCode", TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "IataCode", Text = "IATA Code", Description = null, IsVisible = null, IsReadOnly = null, Sort = null });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 19, ConfigGridId = 3, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 129, FieldIdName = "Demo.RawWikipediaAircraft; IcaoCode", TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "IcaoCode", Text = "ICAO Code", Description = null, IsVisible = null, IsReadOnly = true, Sort = null });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 20, ConfigGridId = 3, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 131, FieldIdName = "Demo.RawWikipediaAircraft; Model", TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "Model", Text = "Image", Description = null, IsVisible = null, IsReadOnly = null, Sort = null });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 21, ConfigGridId = 3, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 134, FieldIdName = "Demo.RawWikipediaAircraft; ModelImageUrl", TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "ModelImageUrl", Text = "Image Link", Description = null, IsVisible = null, IsReadOnly = null, Sort = null });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 22, ConfigGridId = 3, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 133, FieldIdName = "Demo.RawWikipediaAircraft; ModelTitle", TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "ModelTitle", Text = "Title", Description = null, IsVisible = null, IsReadOnly = null, Sort = null });
                result.Add(new FrameworkConfigFieldBuiltIn() { Id = 23, ConfigGridId = 3, ConfigGridIdName = "Demo.RawWikipediaAircraft; ", FieldId = 132, FieldIdName = "Demo.RawWikipediaAircraft; ModelUrl", TableNameCSharp = "Demo.RawWikipediaAircraft", ConfigName = null, FieldNameCSharp = "ModelUrl", Text = "Url", Description = null, IsVisible = null, IsReadOnly = null, Sort = null });
                return result;
            }
        }
    }
}
