// Do not modify this file. It's generated by Framework.Cli.

namespace DatabaseBuiltIn.Demo
{
    using System.Collections.Generic;
    using System.Linq;
    using Framework.DataAccessLayer;
    using Database.Demo;

    public static class LanguageBuiltInTableApplication
    {
        public enum IdNameEnum { [IdNameEnum(null)]None = 0, [IdNameEnum("German")]German = 1, [IdNameEnum("French")]French = 2, [IdNameEnum("English")]English = 3, [IdNameEnum("Italian")]Italian = 4 }

        public static LanguageBuiltIn Row(IdNameEnum value)
        {
            return RowList.Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static List<LanguageBuiltIn> RowList
        {
            get
            {
                var result = new List<LanguageBuiltIn>();
                result.Add(new LanguageBuiltIn() { Id = 1, IdName = "German", Name = "German", TextHtml = "<span class=\"flag-icon flag-icon-de\"></span> German" });
                result.Add(new LanguageBuiltIn() { Id = 2, IdName = "French", Name = "French", TextHtml = "<span class=\"flag-icon flag-icon-fr\"></span> French" });
                result.Add(new LanguageBuiltIn() { Id = 3, IdName = "English", Name = "English", TextHtml = "<span class=\"flag-icon flag-icon-gb\"></span> English" });
                result.Add(new LanguageBuiltIn() { Id = 4, IdName = "Italian", Name = "Italian", TextHtml = "<span class=\"flag-icon flag-icon-it\"></span> Italian" });
                return result;
            }
        }
    }

    public static class LoginPermissionBuiltInTableApplication
    {
        public enum IdNameEnum { [IdNameEnum(null)]None = 0, [IdNameEnum("Calendar Modify")]CalendarModify = 1, [IdNameEnum("Roadmap Modify")]RoadmapModify = 2, [IdNameEnum("Language Modify")]LanguageModify = 3, [IdNameEnum("AirportPage Show")]AirportPageShow = 4 }

        public static LoginPermissionBuiltIn Row(IdNameEnum value)
        {
            return RowList.Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static List<LoginPermissionBuiltIn> RowList
        {
            get
            {
                var result = new List<LoginPermissionBuiltIn>();
                result.Add(new LoginPermissionBuiltIn() { Id = 1, IdName = "Calendar Modify", Name = "Calendar Modify", Description = "Allows user to modify the calendar." });
                result.Add(new LoginPermissionBuiltIn() { Id = 2, IdName = "Roadmap Modify", Name = "Roadmap Modify", Description = "Allows user to modify the development roadmap." });
                result.Add(new LoginPermissionBuiltIn() { Id = 3, IdName = "Language Modify", Name = "Language Modify", Description = "Allows user to add new languages." });
                result.Add(new LoginPermissionBuiltIn() { Id = 4, IdName = "AirportPage Show", Name = "AirportPage Show", Description = "Allows user to see airport page." });
                return result;
            }
        }
    }
}
