// Do not modify this file. It's generated by Framework.Cli.

namespace DatabaseBuiltIn.Demo
{
    using System.Collections.Generic;
    using Database.Demo;

    public static class LanguageBuiltInTableApplication
    {
        public static List<LanguageBuiltIn> RowList
        {
            get
            {
                var result = new List<LanguageBuiltIn>();
                result.Add(new LanguageBuiltIn() { Id = 1, IdName = "German", Name = "German", TextHtml = "<span class=\"flag-icon flag-icon-de\"></span> German" });
                result.Add(new LanguageBuiltIn() { Id = 2, IdName = "French", Name = "French", TextHtml = "<span class=\"flag-icon flag-icon-fr\"></span> French" });
                result.Add(new LanguageBuiltIn() { Id = 3, IdName = "English", Name = "English", TextHtml = "<span class=\"flag-icon flag-icon-gb\"></span> English" });
                result.Add(new LanguageBuiltIn() { Id = 4, IdName = "Italian", Name = "Italian", TextHtml = "<span class=\"flag-icon flag-icon-it\"></span> Italian" });
                return result;
            }
        }
    }

    public static class LoginPermissionBuiltInTableApplication
    {
        public static List<LoginPermissionBuiltIn> RowList
        {
            get
            {
                var result = new List<LoginPermissionBuiltIn>();
                result.Add(new LoginPermissionBuiltIn() { Id = 1, IdName = "Calendar Modify", Name = "Calendar Modify", Description = "Allows user to modify the calendar." });
                result.Add(new LoginPermissionBuiltIn() { Id = 2, IdName = "Roadmap Modify", Name = "Roadmap Modify", Description = "Allows user to modify the development roadmap." });
                result.Add(new LoginPermissionBuiltIn() { Id = 5, IdName = "Language Modify", Name = "Language Modify", Description = "Allows user to add new languages." });
                result.Add(new LoginPermissionBuiltIn() { Id = 6, IdName = "AirportPage Show", Name = "AirportPage Show", Description = "Allows user to see airport page." });
                return result;
            }
        }
    }
}
