// Do not modify this file. It's generated by Framework.Cli.

namespace DatabaseIntegrate.Demo
{
    using System;
    using System.Collections.Generic;
    using System.Globalization;
    using System.Linq;
    using System.Threading.Tasks;
    using Framework.DataAccessLayer;
    using Framework.DataAccessLayer.Integrate;
    using Database.Demo;

    public static class LanguageIntegrateApp
    {
        public enum IdNameEnum { [IdNameEnum(null)]None = 0, [IdNameEnum("English")]English = -1, [IdNameEnum("French")]French = -2, [IdNameEnum("German")]German = -3, [IdNameEnum("Italian")]Italian = -4 }

        public static LanguageIntegrate Row(this IdNameEnum value)
        {
            return RowList.Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static IdNameEnum IdName(string value)
        {
            return IdNameEnumAttribute.IdNameToEnum<IdNameEnum>(value);
        }

        public static string IdName(this IdNameEnum value)
        {
            return IdNameEnumAttribute.IdNameFromEnum(value);
        }

        public static async Task<int> Id(this IdNameEnum value)
        {
            return (await Data.Query<LanguageIntegrate>().Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).QueryExecuteAsync()).Single().Id;
        }

        public static List<LanguageIntegrate> RowList
        {
            get
            {
                var result = new List<LanguageIntegrate>
                {
                    new LanguageIntegrate { Id = 0, IdName = "English", Name = "English", TextHtml = "<span class=\"flag-icon flag-icon-gb\"></span> English" },
                    new LanguageIntegrate { Id = 0, IdName = "French", Name = "French", TextHtml = "<span class=\"flag-icon flag-icon-fr\"></span> French" },
                    new LanguageIntegrate { Id = 0, IdName = "German", Name = "German", TextHtml = "<span class=\"flag-icon flag-icon-de\"></span> German" },
                    new LanguageIntegrate { Id = 0, IdName = "Italian", Name = "Italian", TextHtml = "<span class=\"flag-icon flag-icon-it\"></span> Italian" },
                };
                return result;
            }
        }
    }

    public static class LoginPermissionIntegrateApp
    {
        public enum IdNameEnum { [IdNameEnum(null)]None = 0, [IdNameEnum("Administrator")]Administrator = -1, [IdNameEnum("Developer")]Developer = -2, [IdNameEnum("Guest")]Guest = -3 }

        public static LoginPermissionIntegrate Row(this IdNameEnum value)
        {
            return RowList.Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static IdNameEnum IdName(string value)
        {
            return IdNameEnumAttribute.IdNameToEnum<IdNameEnum>(value);
        }

        public static string IdName(this IdNameEnum value)
        {
            return IdNameEnumAttribute.IdNameFromEnum(value);
        }

        public static async Task<int> Id(this IdNameEnum value)
        {
            return (await Data.Query<LoginPermissionIntegrate>().Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).QueryExecuteAsync()).Single().Id;
        }

        public static List<LoginPermissionIntegrate> RowList
        {
            get
            {
                var result = new List<LoginPermissionIntegrate>
                {
                    new LoginPermissionIntegrate { Id = 0, IdName = "Administrator", Name = "Administrator", Description = "Administrator permission", IsIntegrate = true, IsExist = true },
                    new LoginPermissionIntegrate { Id = 0, IdName = "Developer", Name = "Developer", Description = "Developer permission", IsIntegrate = true, IsExist = true },
                    new LoginPermissionIntegrate { Id = 0, IdName = "Guest", Name = "Guest", Description = "Guest permission", IsIntegrate = true, IsExist = true },
                };
                return result;
            }
        }
    }

    public static class RoadmapCategoryIntegrateApp
    {
        public enum IdNameEnum { [IdNameEnum(null)]None = 0, [IdNameEnum("Analyze")]Analyze = -1, [IdNameEnum("Bug")]Bug = -2, [IdNameEnum("Feature")]Feature = -3 }

        public static RoadmapCategoryIntegrate Row(this IdNameEnum value)
        {
            return RowList.Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static IdNameEnum IdName(string value)
        {
            return IdNameEnumAttribute.IdNameToEnum<IdNameEnum>(value);
        }

        public static string IdName(this IdNameEnum value)
        {
            return IdNameEnumAttribute.IdNameFromEnum(value);
        }

        public static async Task<int> Id(this IdNameEnum value)
        {
            return (await Data.Query<RoadmapCategoryIntegrate>().Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).QueryExecuteAsync()).Single().Id;
        }

        public static List<RoadmapCategoryIntegrate> RowList
        {
            get
            {
                var result = new List<RoadmapCategoryIntegrate>
                {
                    new RoadmapCategoryIntegrate { Id = 0, IdName = "Analyze", Name = "Analyze", Text = "Analyze", Description = "Analyze", IsIntegrate = true, IsExist = true },
                    new RoadmapCategoryIntegrate { Id = 0, IdName = "Bug", Name = "Bug", Text = "Bug", Description = "Software Bug", IsIntegrate = true, IsExist = true },
                    new RoadmapCategoryIntegrate { Id = 0, IdName = "Feature", Name = "Feature", Text = "Feature", Description = "Software Feature", IsIntegrate = true, IsExist = true },
                };
                return result;
            }
        }
    }

    public static class RoadmapModuleIntegrateApp
    {
        public enum IdNameEnum { [IdNameEnum(null)]None = 0, [IdNameEnum("Application")]Application = -1, [IdNameEnum("ApplicationCms")]ApplicationCms = -2, [IdNameEnum("ApplicationLogin")]ApplicationLogin = -3, [IdNameEnum("ApplicationRoadmap")]ApplicationRoadmap = -4, [IdNameEnum("Framework")]Framework = -5 }

        public static RoadmapModuleIntegrate Row(this IdNameEnum value)
        {
            return RowList.Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static IdNameEnum IdName(string value)
        {
            return IdNameEnumAttribute.IdNameToEnum<IdNameEnum>(value);
        }

        public static string IdName(this IdNameEnum value)
        {
            return IdNameEnumAttribute.IdNameFromEnum(value);
        }

        public static async Task<int> Id(this IdNameEnum value)
        {
            return (await Data.Query<RoadmapModuleIntegrate>().Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).QueryExecuteAsync()).Single().Id;
        }

        public static List<RoadmapModuleIntegrate> RowList
        {
            get
            {
                var result = new List<RoadmapModuleIntegrate>
                {
                    new RoadmapModuleIntegrate { Id = 0, IdName = "Application", Name = "Application", Text = "Application", Description = null, IsIntegrate = true, IsExist = true },
                    new RoadmapModuleIntegrate { Id = 0, IdName = "ApplicationCms", Name = "ApplicationCms", Text = "Application / Cms", Description = null, IsIntegrate = true, IsExist = true },
                    new RoadmapModuleIntegrate { Id = 0, IdName = "ApplicationLogin", Name = "ApplicationLogin", Text = "Application / Login", Description = null, IsIntegrate = true, IsExist = true },
                    new RoadmapModuleIntegrate { Id = 0, IdName = "ApplicationRoadmap", Name = "ApplicationRoadmap", Text = "Application / Roadmap", Description = null, IsIntegrate = true, IsExist = true },
                    new RoadmapModuleIntegrate { Id = 0, IdName = "Framework", Name = "Framework", Text = "Framework", Description = null, IsIntegrate = true, IsExist = true },
                };
                return result;
            }
        }
    }

    public static class RoadmapPriorityIntegrateApp
    {
        public enum IdNameEnum { [IdNameEnum(null)]None = 0, [IdNameEnum("Critical")]Critical = -1, [IdNameEnum("High")]High = -2, [IdNameEnum("Low")]Low = -3, [IdNameEnum("Medium")]Medium = -4 }

        public static RoadmapPriorityIntegrate Row(this IdNameEnum value)
        {
            return RowList.Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static IdNameEnum IdName(string value)
        {
            return IdNameEnumAttribute.IdNameToEnum<IdNameEnum>(value);
        }

        public static string IdName(this IdNameEnum value)
        {
            return IdNameEnumAttribute.IdNameFromEnum(value);
        }

        public static async Task<int> Id(this IdNameEnum value)
        {
            return (await Data.Query<RoadmapPriorityIntegrate>().Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).QueryExecuteAsync()).Single().Id;
        }

        public static List<RoadmapPriorityIntegrate> RowList
        {
            get
            {
                var result = new List<RoadmapPriorityIntegrate>
                {
                    new RoadmapPriorityIntegrate { Id = 0, IdName = "Critical", Name = "Critical", Text = "Critical (Red)", Description = null, IsIntegrate = true, IsExist = true },
                    new RoadmapPriorityIntegrate { Id = 0, IdName = "High", Name = "High", Text = "High (Orange)", Description = null, IsIntegrate = true, IsExist = true },
                    new RoadmapPriorityIntegrate { Id = 0, IdName = "Low", Name = "Low", Text = "Low (Green)", Description = null, IsIntegrate = true, IsExist = true },
                    new RoadmapPriorityIntegrate { Id = 0, IdName = "Medium", Name = "Medium", Text = "Medium (Blue)", Description = null, IsIntegrate = true, IsExist = true },
                };
                return result;
            }
        }
    }

    public static class RoadmapStateIntegrateApp
    {
        public enum IdNameEnum { [IdNameEnum(null)]None = 0, [IdNameEnum("Done")]Done = -1, [IdNameEnum("In Progress")]InProgress = -2, [IdNameEnum("New")]New = -3, [IdNameEnum("Open")]Open = -4 }

        public static RoadmapStateIntegrate Row(this IdNameEnum value)
        {
            return RowList.Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static IdNameEnum IdName(string value)
        {
            return IdNameEnumAttribute.IdNameToEnum<IdNameEnum>(value);
        }

        public static string IdName(this IdNameEnum value)
        {
            return IdNameEnumAttribute.IdNameFromEnum(value);
        }

        public static async Task<int> Id(this IdNameEnum value)
        {
            return (await Data.Query<RoadmapStateIntegrate>().Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).QueryExecuteAsync()).Single().Id;
        }

        public static List<RoadmapStateIntegrate> RowList
        {
            get
            {
                var result = new List<RoadmapStateIntegrate>
                {
                    new RoadmapStateIntegrate { Id = 0, IdName = "Done", Name = "Done", Text = "Done", Description = null, IsIntegrate = true, IsExist = true },
                    new RoadmapStateIntegrate { Id = 0, IdName = "In Progress", Name = "In Progress", Text = "In Progress", Description = null, IsIntegrate = true, IsExist = true },
                    new RoadmapStateIntegrate { Id = 0, IdName = "New", Name = "New", Text = "New", Description = null, IsIntegrate = true, IsExist = true },
                    new RoadmapStateIntegrate { Id = 0, IdName = "Open", Name = "Open", Text = "Open", Description = null, IsIntegrate = true, IsExist = true },
                };
                return result;
            }
        }
    }

    public static class CmsComponentTypeIntegrateApp
    {
        public enum IdNameEnum { [IdNameEnum(null)]None = 0, [IdNameEnum("Page")]Page = -1, [IdNameEnum("Paragraph")]Paragraph = -2, [IdNameEnum("Bullet")]Bullet = -3, [IdNameEnum("Image")]Image = -4, [IdNameEnum("Youtube")]Youtube = -5, [IdNameEnum("CodeBlock")]CodeBlock = -6, [IdNameEnum("Glossary")]Glossary = -7 }

        public static CmsComponentTypeIntegrate Row(this IdNameEnum value)
        {
            return RowList.Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).SingleOrDefault();
        }

        public static IdNameEnum IdName(string value)
        {
            return IdNameEnumAttribute.IdNameToEnum<IdNameEnum>(value);
        }

        public static string IdName(this IdNameEnum value)
        {
            return IdNameEnumAttribute.IdNameFromEnum(value);
        }

        public static async Task<int> Id(this IdNameEnum value)
        {
            return (await Data.Query<CmsComponentTypeIntegrate>().Where(item => item.IdName == IdNameEnumAttribute.IdNameFromEnum(value)).QueryExecuteAsync()).Single().Id;
        }

        public static List<CmsComponentTypeIntegrate> RowList
        {
            get
            {
                var result = new List<CmsComponentTypeIntegrate>
                {
                    new CmsComponentTypeIntegrate { Id = 0, Name = "Page", Sort = 1, IdName = "Page" },
                    new CmsComponentTypeIntegrate { Id = 0, Name = "Paragraph", Sort = 2, IdName = "Paragraph" },
                    new CmsComponentTypeIntegrate { Id = 0, Name = "Bullet", Sort = 3, IdName = "Bullet" },
                    new CmsComponentTypeIntegrate { Id = 0, Name = "Image", Sort = 4, IdName = "Image" },
                    new CmsComponentTypeIntegrate { Id = 0, Name = "Youtube", Sort = 5, IdName = "Youtube" },
                    new CmsComponentTypeIntegrate { Id = 0, Name = "CodeBlock", Sort = 6, IdName = "CodeBlock" },
                    new CmsComponentTypeIntegrate { Id = 0, Name = "Glossary", Sort = 7, IdName = "Glossary" },
                };
                return result;
            }
        }
    }
}
