GO
SET IDENTITY_INSERT [dbo].[Country] ON 
GO
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (1, N'Andorra', N'AD', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (2, N'United Arab Emirates', N'AE', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (3, N'Afghanistan', N'AF', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (4, N'Antigua and Barbuda', N'AG', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (5, N'Anguilla', N'AI', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (6, N'Albania', N'AL', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (7, N'Armenia', N'AM', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (8, N'Angola', N'AO', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (9, N'Antarctica', N'AQ', N'AN')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (10, N'Argentina', N'AR', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (11, N'American Samoa', N'AS', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (12, N'Austria', N'AT', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (13, N'Australia', N'AU', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (14, N'Aruba', N'AW', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (15, N'Azerbaijan', N'AZ', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (16, N'Bosnia and Herzegovina', N'BA', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (17, N'Barbados', N'BB', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (18, N'Bangladesh', N'BD', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (19, N'Belgium', N'BE', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (20, N'Burkina Faso', N'BF', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (21, N'Bulgaria', N'BG', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (22, N'Bahrain', N'BH', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (23, N'Burundi', N'BI', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (24, N'Benin', N'BJ', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (25, N'Saint Barthélemy', N'BL', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (26, N'Bermuda', N'BM', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (27, N'Brunei', N'BN', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (28, N'Bolivia', N'BO', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (29, N'Caribbean Netherlands', N'BQ', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (30, N'Brazil', N'BR', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (31, N'Bahamas', N'BS', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (32, N'Bhutan', N'BT', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (33, N'Botswana', N'BW', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (34, N'Belarus', N'BY', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (35, N'Belize', N'BZ', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (36, N'Canada', N'CA', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (37, N'Cocos (Keeling) Islands', N'CC', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (38, N'Congo (Kinshasa)', N'CD', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (39, N'Central African Republic', N'CF', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (40, N'Congo (Brazzaville)', N'CG', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (41, N'Switzerland', N'CH', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (42, N'Côte d''Ivoire', N'CI', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (43, N'Cook Islands', N'CK', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (44, N'Chile', N'CL', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (45, N'Cameroon', N'CM', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (46, N'China', N'CN', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (47, N'Colombia', N'CO', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (48, N'Costa Rica', N'CR', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (49, N'Cuba', N'CU', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (50, N'Cape Verde', N'CV', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (51, N'Curaçao', N'CW', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (52, N'Christmas Island', N'CX', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (53, N'Cyprus', N'CY', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (54, N'Czech Republic', N'CZ', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (55, N'Germany', N'DE', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (56, N'Djibouti', N'DJ', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (57, N'Denmark', N'DK', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (58, N'Dominica', N'DM', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (59, N'Dominican Republic', N'DO', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (60, N'Algeria', N'DZ', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (61, N'Ecuador', N'EC', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (62, N'Estonia', N'EE', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (63, N'Egypt', N'EG', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (64, N'Western Sahara', N'EH', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (65, N'Eritrea', N'ER', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (66, N'Spain', N'ES', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (67, N'Ethiopia', N'ET', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (68, N'Finland', N'FI', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (69, N'Fiji', N'FJ', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (70, N'Falkland Islands', N'FK', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (71, N'Micronesia', N'FM', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (72, N'Faroe Islands', N'FO', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (73, N'France', N'FR', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (74, N'Gabon', N'GA', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (75, N'United Kingdom', N'GB', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (76, N'Grenada', N'GD', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (77, N'Georgia', N'GE', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (78, N'French Guiana', N'GF', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (79, N'Guernsey', N'GG', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (80, N'Ghana', N'GH', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (81, N'Gibraltar', N'GI', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (82, N'Greenland', N'GL', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (83, N'Gambia', N'GM', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (84, N'Guinea', N'GN', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (85, N'Guadeloupe', N'GP', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (86, N'Equatorial Guinea', N'GQ', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (87, N'Greece', N'GR', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (88, N'South Georgia and the South Sandwich Islands', N'GS', N'AN')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (89, N'Guatemala', N'GT', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (90, N'Guam', N'GU', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (91, N'Guinea-Bissau', N'GW', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (92, N'Guyana', N'GY', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (93, N'Hong Kong', N'HK', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (94, N'Honduras', N'HN', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (95, N'Croatia', N'HR', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (96, N'Haiti', N'HT', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (97, N'Hungary', N'HU', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (98, N'Indonesia', N'ID', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (99, N'Ireland', N'IE', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (100, N'Israel', N'IL', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (101, N'Isle of Man', N'IM', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (102, N'India', N'IN', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (103, N'British Indian Ocean Territory', N'IO', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (104, N'Iraq', N'IQ', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (105, N'Iran', N'IR', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (106, N'Iceland', N'IS', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (107, N'Italy', N'IT', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (108, N'Jersey', N'JE', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (109, N'Jamaica', N'JM', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (110, N'Jordan', N'JO', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (111, N'Japan', N'JP', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (112, N'Kenya', N'KE', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (113, N'Kyrgyzstan', N'KG', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (114, N'Cambodia', N'KH', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (115, N'Kiribati', N'KI', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (116, N'Comoros', N'KM', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (117, N'Saint Kitts and Nevis', N'KN', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (118, N'North Korea', N'KP', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (119, N'South Korea', N'KR', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (120, N'Kosovo', N'KS', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (121, N'Kuwait', N'KW', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (122, N'Cayman Islands', N'KY', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (123, N'Kazakhstan', N'KZ', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (124, N'Laos', N'LA', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (125, N'Lebanon', N'LB', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (126, N'Saint Lucia', N'LC', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (127, N'Liechtenstein', N'LI', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (128, N'Sri Lanka', N'LK', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (129, N'Liberia', N'LR', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (130, N'Lesotho', N'LS', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (131, N'Lithuania', N'LT', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (132, N'Luxembourg', N'LU', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (133, N'Latvia', N'LV', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (134, N'Libya', N'LY', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (135, N'Morocco', N'MA', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (136, N'Monaco', N'MC', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (137, N'Moldova', N'MD', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (138, N'Montenegro', N'ME', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (139, N'Saint Martin', N'MF', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (140, N'Madagascar', N'MG', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (141, N'Marshall Islands', N'MH', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (142, N'Macedonia', N'MK', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (143, N'Mali', N'ML', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (144, N'Burma', N'MM', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (145, N'Mongolia', N'MN', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (146, N'Macau', N'MO', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (147, N'Northern Mariana Islands', N'MP', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (148, N'Martinique', N'MQ', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (149, N'Mauritania', N'MR', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (150, N'Montserrat', N'MS', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (151, N'Malta', N'MT', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (152, N'Mauritius', N'MU', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (153, N'Maldives', N'MV', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (154, N'Malawi', N'MW', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (155, N'Mexico', N'MX', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (156, N'Malaysia', N'MY', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (157, N'Mozambique', N'MZ', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (158, N'Namibia', N'NA', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (159, N'New Caledonia', N'NC', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (160, N'Niger', N'NE', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (161, N'Norfolk Island', N'NF', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (162, N'Nigeria', N'NG', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (163, N'Nicaragua', N'NI', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (164, N'Netherlands', N'NL', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (165, N'Norway', N'NO', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (166, N'Nepal', N'NP', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (167, N'Nauru', N'NR', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (168, N'Niue', N'NU', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (169, N'New Zealand', N'NZ', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (170, N'Oman', N'OM', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (171, N'Panama', N'PA', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (172, N'Perú', N'PE', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (173, N'French Polynesia', N'PF', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (174, N'Papua New Guinea', N'PG', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (175, N'Philippines', N'PH', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (176, N'Pakistan', N'PK', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (177, N'Poland', N'PL', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (178, N'Saint Pierre and Miquelon', N'PM', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (179, N'Pitcairn', N'PN', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (180, N'Puerto Rico', N'PR', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (181, N'Palestinian Territory', N'PS', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (182, N'Portugal', N'PT', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (183, N'Palau', N'PW', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (184, N'Paraguay', N'PY', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (185, N'Qatar', N'QA', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (186, N'Réunion', N'RE', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (187, N'Romania', N'RO', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (188, N'Serbia', N'RS', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (189, N'Russia', N'RU', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (190, N'Rwanda', N'RW', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (191, N'Saudi Arabia', N'SA', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (192, N'Solomon Islands', N'SB', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (193, N'Seychelles', N'SC', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (194, N'Sudan', N'SD', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (195, N'Sweden', N'SE', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (196, N'Singapore', N'SG', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (197, N'Saint Helena', N'SH', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (198, N'Slovenia', N'SI', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (199, N'Slovakia', N'SK', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (200, N'Sierra Leone', N'SL', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (201, N'San Marino', N'SM', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (202, N'Senegal', N'SN', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (203, N'Somalia', N'SO', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (204, N'Suriname', N'SR', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (205, N'South Sudan', N'SS', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (206, N'São Tomé and Principe', N'ST', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (207, N'El Salvador', N'SV', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (208, N'Sint Maarten', N'SX', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (209, N'Syria', N'SY', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (210, N'Swaziland', N'SZ', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (211, N'Turks and Caicos Islands', N'TC', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (212, N'Chad', N'TD', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (213, N'French Southern Territories', N'TF', N'AN')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (214, N'Togo', N'TG', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (215, N'Thailand', N'TH', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (216, N'Tajikistan', N'TJ', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (217, N'Tokelau', N'TK', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (218, N'Timor-Leste', N'TL', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (219, N'Turkmenistan', N'TM', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (220, N'Tunisia', N'TN', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (221, N'Tonga', N'TO', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (222, N'Turkey', N'TR', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (223, N'Trinidad and Tobago', N'TT', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (224, N'Tuvalu', N'TV', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (225, N'Taiwan', N'TW', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (226, N'Tanzania', N'TZ', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (227, N'Ukraine', N'UA', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (228, N'Uganda', N'UG', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (229, N'United States Minor Outlying Islands', N'UM', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (230, N'United States', N'US', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (231, N'Uruguay', N'UY', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (232, N'Uzbekistan', N'UZ', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (233, N'Vatican City', N'VA', N'EU')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (234, N'Saint Vincent and the Grenadines', N'VC', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (235, N'Venezuela', N'VE', N'SA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (236, N'British Virgin Islands', N'VG', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (237, N'U.S. Virgin Islands', N'VI', N'NA')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (238, N'Vietnam', N'VN', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (239, N'Vanuatu', N'VU', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (240, N'Wallis and Futuna', N'WF', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (241, N'Samoa', N'WS', N'OC')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (242, N'Yemen', N'YE', N'AS')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (243, N'Mayotte', N'YT', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (244, N'South Africa', N'ZA', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (245, N'Zambia', N'ZM', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (246, N'Zimbabwe', N'ZW', N'AF')
INSERT [dbo].[Country] ([Id], [Text], [TextShort], [Continent]) VALUES (247, N'Unknown or unassigned country', N'ZZ', N'AF')
GO
SET IDENTITY_INSERT [dbo].[Country] OFF
GO
