DROP VIEW Demo.LoginUserPermissionDisplay
DROP VIEW Demo.LoginRolePermissionDisplay
DROP VIEW Demo.LoginUserRoleDisplay
DROP VIEW Demo.LoginRolePermissionIntegrate
DROP TABLE Demo.LoginRolePermission
DROP VIEW Demo.LoginUserRoleIntegrate
DROP TABLE Demo.LoginUserRole
DROP VIEW Demo.LoginPermissionIntegrate
DROP TABLE Demo.LoginPermission
DROP VIEW Demo.LoginRoleIntegrate
DROP TABLE Demo.LoginRole
DROP VIEW Demo.LoginUserIntegrate
DROP TABLE Demo.LoginUser
