DROP VIEW Demo.RoadmapDisplay
DROP VIEW Demo.RoadmapIntegrate
DROP TABLE Demo.Roadmap
DROP VIEW Demo.RoadmapModuleIntegrate
DROP TABLE Demo.RoadmapModule
DROP VIEW Demo.RoadmapPriorityIntegrate
DROP TABLE Demo.RoadmapPriority
DROP VIEW Demo.RoadmapStateIntegrate
DROP TABLE Demo.RoadmapState
DROP VIEW Demo.RoadmapCategoryIntegrate
DROP TABLE Demo.RoadmapCategory
