GO
CREATE TABLE Demo.StorageFile
(
	Id INT PRIMARY KEY IDENTITY,
	FileName NVARCHAR(256) UNIQUE,
	Data VARBINARY(MAX),
	Description NVARCHAR(256),
	IsIntegrate BIT NOT NULL,
	IsDelete BIT NOT NULL,
)
