DROP VIEW Demo.CmsComponentDisplay
DROP VIEW Demo.CmsComponentBuiltIn
DROP TABLE Demo.CmsComponent
DROP VIEW Demo.CmsFileDisplay
DROP VIEW Demo.CmsFileBuiltIn
DROP TABLE Demo.CmsFile
DROP VIEW Demo.CmsCodeBlockTypeBuiltIn
DROP TABLE Demo.CmsCodeBlockType
DROP VIEW Demo.CmsComponentTypeBuiltIn
DROP TABLE Demo.CmsComponentType
